#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build            Generates a Makefile w/ all jobs as targets"
	@echo "implement        Implement design and generate bitstream for FPGA"
	@echo "upload           Upload design to FPGA"
	@echo "upload-remote    Upload design to FPGA"
	@echo "sim              Simulate fpga design w/ simple test"
	@echo "waves            Open simvision"
	@echo "clean            Cleans directory"
	@echo "hw_server        Starts hardware server"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------

#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "implement" 
#----------------------------------------------------------
implement: 
	toolbox-cli --color -l info -b build -o toolbox implement	
.PHONY: implement
#----------------------------------------------------------

#----------------------------------------------------------
# Target "upload" 
#----------------------------------------------------------
upload: 
	toolbox-cli --color -l info -b build -o toolbox upload	
.PHONY: upload
#----------------------------------------------------------

#----------------------------------------------------------
# Target "upload-remote" 
#----------------------------------------------------------
upload-remote: 
	toolbox-cli --color -l info -b build -o toolbox upload-remote	
.PHONY: upload-remote
#----------------------------------------------------------

#----------------------------------------------------------
# Target "sim" 
#----------------------------------------------------------
sim: 
	toolbox-cli --color -l info -b build -o toolbox sim	
.PHONY: sim
#----------------------------------------------------------

#----------------------------------------------------------
# Target "waves" 
#----------------------------------------------------------
waves: 
	toolbox-cli --color -l info -b build -o toolbox waves	
.PHONY: waves
#----------------------------------------------------------

#----------------------------------------------------------
# Target "clean" 
#----------------------------------------------------------
clean: 
	rm -rf build *.jou *.log __pycache__	
.PHONY: clean
#----------------------------------------------------------

#----------------------------------------------------------
# Target "hw_server" 
#----------------------------------------------------------
hw_server: 
	hw_server -d -s tcp::3121	
.PHONY: hw_server
#----------------------------------------------------------

