// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-05-25 15:25:15.290170
// Configuration File: config.yml
// Memory Name: ssp1_controller_uart
// Memory Word Width: 8
// Address Range: 256
`default_nettype none

/****************************************/
/* Module: ssp1_controller_uart_mem_map */
/****************************************/
module ssp1_controller_uart_mem_map
(
input wire [7:0] ssp1_controller_uart_write_mem [255:0],
output wire [7:0] ssp1_controller_uart_read_mem [255:0],
output wire reset,
output wire [7:0] leds,
output wire shifter_oe_n,
output wire scan_cg_en,
input wire [27:0] loopback_so_data_0,
input wire [27:0] loopback_so_data_1,
input wire [27:0] loopback_so_data_2,
input wire [27:0] loopback_so_data_3,
output wire [1:0] scan_in_addr_address_0_r0,
output wire [3:0] scan_in_addr_lb_sel_0_r0,
output wire scan_in_addr_enable_0_r0,
output wire [1:0] scan_in_addr_address_0_r1,
output wire [3:0] scan_in_addr_lb_sel_0_r1,
output wire scan_in_addr_enable_0_r1,
output wire [1:0] scan_in_addr_address_0_r2,
output wire [3:0] scan_in_addr_lb_sel_0_r2,
output wire scan_in_addr_enable_0_r2,
output wire [1:0] scan_in_addr_address_0_r3,
output wire [3:0] scan_in_addr_lb_sel_0_r3,
output wire scan_in_addr_enable_0_r3,
output wire scan_in_addr_req_0,
input wire scan_in_addr_ack_0,
output wire [1:0] scan_in_addr_cmd_0,
output wire [1:0] scan_in_addr_address_1_r0,
output wire [3:0] scan_in_addr_lb_sel_1_r0,
output wire scan_in_addr_enable_1_r0,
output wire [1:0] scan_in_addr_address_1_r1,
output wire [3:0] scan_in_addr_lb_sel_1_r1,
output wire scan_in_addr_enable_1_r1,
output wire [1:0] scan_in_addr_address_1_r2,
output wire [3:0] scan_in_addr_lb_sel_1_r2,
output wire scan_in_addr_enable_1_r2,
output wire [1:0] scan_in_addr_address_1_r3,
output wire [3:0] scan_in_addr_lb_sel_1_r3,
output wire scan_in_addr_enable_1_r3,
output wire scan_in_addr_req_1,
input wire scan_in_addr_ack_1,
output wire [1:0] scan_in_addr_cmd_1,
output wire [1:0] scan_in_addr_address_2_r0,
output wire [3:0] scan_in_addr_lb_sel_2_r0,
output wire scan_in_addr_enable_2_r0,
output wire [1:0] scan_in_addr_address_2_r1,
output wire [3:0] scan_in_addr_lb_sel_2_r1,
output wire scan_in_addr_enable_2_r1,
output wire [1:0] scan_in_addr_address_2_r2,
output wire [3:0] scan_in_addr_lb_sel_2_r2,
output wire scan_in_addr_enable_2_r2,
output wire [1:0] scan_in_addr_address_2_r3,
output wire [3:0] scan_in_addr_lb_sel_2_r3,
output wire scan_in_addr_enable_2_r3,
output wire scan_in_addr_req_2,
input wire scan_in_addr_ack_2,
output wire [1:0] scan_in_addr_cmd_2,
output wire [1:0] scan_in_addr_address_3_r0,
output wire [3:0] scan_in_addr_lb_sel_3_r0,
output wire scan_in_addr_enable_3_r0,
output wire [1:0] scan_in_addr_address_3_r1,
output wire [3:0] scan_in_addr_lb_sel_3_r1,
output wire scan_in_addr_enable_3_r1,
output wire [1:0] scan_in_addr_address_3_r2,
output wire [3:0] scan_in_addr_lb_sel_3_r2,
output wire scan_in_addr_enable_3_r2,
output wire [1:0] scan_in_addr_address_3_r3,
output wire [3:0] scan_in_addr_lb_sel_3_r3,
output wire scan_in_addr_enable_3_r3,
output wire scan_in_addr_req_3,
input wire scan_in_addr_ack_3,
output wire [1:0] scan_in_addr_cmd_3,
output wire [6:0] scan_in_inst_0_data_0,
output wire [6:0] scan_in_inst_1_data_0,
output wire [6:0] scan_in_inst_2_data_0,
output wire [6:0] scan_in_inst_3_data_0,
output wire [6:0] scan_in_inst_4_data_0,
output wire [6:0] scan_in_inst_5_data_0,
output wire [6:0] scan_in_inst_6_data_0,
output wire [6:0] scan_in_inst_7_data_0,
output wire [6:0] scan_in_inst_8_data_0,
output wire [6:0] scan_in_inst_9_data_0,
output wire [6:0] scan_in_inst_10_data_0,
output wire [6:0] scan_in_inst_11_data_0,
output wire [6:0] scan_in_inst_12_data_0,
output wire [6:0] scan_in_inst_13_data_0,
output wire [6:0] scan_in_inst_14_data_0,
output wire [6:0] scan_in_inst_15_data_0,
output wire [6:0] scan_in_inst_16_data_0,
output wire [6:0] scan_in_inst_17_data_0,
output wire [6:0] scan_in_inst_18_data_0,
output wire [6:0] scan_in_inst_19_data_0,
output wire [6:0] scan_in_inst_20_data_0,
output wire [6:0] scan_in_inst_21_data_0,
output wire [6:0] scan_in_inst_22_data_0,
output wire [6:0] scan_in_inst_23_data_0,
output wire [6:0] scan_in_inst_24_data_0,
output wire [6:0] scan_in_inst_25_data_0,
output wire [6:0] scan_in_inst_26_data_0,
output wire [6:0] scan_in_inst_27_data_0,
output wire [6:0] scan_in_inst_28_data_0,
output wire [6:0] scan_in_inst_29_data_0,
output wire [6:0] scan_in_inst_30_data_0,
output wire [6:0] scan_in_inst_31_data_0,
output wire scan_in_inst_req_0,
input wire scan_in_inst_ack_0,
output wire [1:0] scan_in_inst_cmd_0,
output wire [6:0] scan_in_inst_0_data_1,
output wire [6:0] scan_in_inst_1_data_1,
output wire [6:0] scan_in_inst_2_data_1,
output wire [6:0] scan_in_inst_3_data_1,
output wire [6:0] scan_in_inst_4_data_1,
output wire [6:0] scan_in_inst_5_data_1,
output wire [6:0] scan_in_inst_6_data_1,
output wire [6:0] scan_in_inst_7_data_1,
output wire [6:0] scan_in_inst_8_data_1,
output wire [6:0] scan_in_inst_9_data_1,
output wire [6:0] scan_in_inst_10_data_1,
output wire [6:0] scan_in_inst_11_data_1,
output wire [6:0] scan_in_inst_12_data_1,
output wire [6:0] scan_in_inst_13_data_1,
output wire [6:0] scan_in_inst_14_data_1,
output wire [6:0] scan_in_inst_15_data_1,
output wire [6:0] scan_in_inst_16_data_1,
output wire [6:0] scan_in_inst_17_data_1,
output wire [6:0] scan_in_inst_18_data_1,
output wire [6:0] scan_in_inst_19_data_1,
output wire [6:0] scan_in_inst_20_data_1,
output wire [6:0] scan_in_inst_21_data_1,
output wire [6:0] scan_in_inst_22_data_1,
output wire [6:0] scan_in_inst_23_data_1,
output wire [6:0] scan_in_inst_24_data_1,
output wire [6:0] scan_in_inst_25_data_1,
output wire [6:0] scan_in_inst_26_data_1,
output wire [6:0] scan_in_inst_27_data_1,
output wire [6:0] scan_in_inst_28_data_1,
output wire [6:0] scan_in_inst_29_data_1,
output wire [6:0] scan_in_inst_30_data_1,
output wire [6:0] scan_in_inst_31_data_1,
output wire scan_in_inst_req_1,
input wire scan_in_inst_ack_1,
output wire [1:0] scan_in_inst_cmd_1,
output wire [6:0] scan_in_inst_0_data_2,
output wire [6:0] scan_in_inst_1_data_2,
output wire [6:0] scan_in_inst_2_data_2,
output wire [6:0] scan_in_inst_3_data_2,
output wire [6:0] scan_in_inst_4_data_2,
output wire [6:0] scan_in_inst_5_data_2,
output wire [6:0] scan_in_inst_6_data_2,
output wire [6:0] scan_in_inst_7_data_2,
output wire [6:0] scan_in_inst_8_data_2,
output wire [6:0] scan_in_inst_9_data_2,
output wire [6:0] scan_in_inst_10_data_2,
output wire [6:0] scan_in_inst_11_data_2,
output wire [6:0] scan_in_inst_12_data_2,
output wire [6:0] scan_in_inst_13_data_2,
output wire [6:0] scan_in_inst_14_data_2,
output wire [6:0] scan_in_inst_15_data_2,
output wire [6:0] scan_in_inst_16_data_2,
output wire [6:0] scan_in_inst_17_data_2,
output wire [6:0] scan_in_inst_18_data_2,
output wire [6:0] scan_in_inst_19_data_2,
output wire [6:0] scan_in_inst_20_data_2,
output wire [6:0] scan_in_inst_21_data_2,
output wire [6:0] scan_in_inst_22_data_2,
output wire [6:0] scan_in_inst_23_data_2,
output wire [6:0] scan_in_inst_24_data_2,
output wire [6:0] scan_in_inst_25_data_2,
output wire [6:0] scan_in_inst_26_data_2,
output wire [6:0] scan_in_inst_27_data_2,
output wire [6:0] scan_in_inst_28_data_2,
output wire [6:0] scan_in_inst_29_data_2,
output wire [6:0] scan_in_inst_30_data_2,
output wire [6:0] scan_in_inst_31_data_2,
output wire scan_in_inst_req_2,
input wire scan_in_inst_ack_2,
output wire [1:0] scan_in_inst_cmd_2,
output wire [6:0] scan_in_inst_0_data_3,
output wire [6:0] scan_in_inst_1_data_3,
output wire [6:0] scan_in_inst_2_data_3,
output wire [6:0] scan_in_inst_3_data_3,
output wire [6:0] scan_in_inst_4_data_3,
output wire [6:0] scan_in_inst_5_data_3,
output wire [6:0] scan_in_inst_6_data_3,
output wire [6:0] scan_in_inst_7_data_3,
output wire [6:0] scan_in_inst_8_data_3,
output wire [6:0] scan_in_inst_9_data_3,
output wire [6:0] scan_in_inst_10_data_3,
output wire [6:0] scan_in_inst_11_data_3,
output wire [6:0] scan_in_inst_12_data_3,
output wire [6:0] scan_in_inst_13_data_3,
output wire [6:0] scan_in_inst_14_data_3,
output wire [6:0] scan_in_inst_15_data_3,
output wire [6:0] scan_in_inst_16_data_3,
output wire [6:0] scan_in_inst_17_data_3,
output wire [6:0] scan_in_inst_18_data_3,
output wire [6:0] scan_in_inst_19_data_3,
output wire [6:0] scan_in_inst_20_data_3,
output wire [6:0] scan_in_inst_21_data_3,
output wire [6:0] scan_in_inst_22_data_3,
output wire [6:0] scan_in_inst_23_data_3,
output wire [6:0] scan_in_inst_24_data_3,
output wire [6:0] scan_in_inst_25_data_3,
output wire [6:0] scan_in_inst_26_data_3,
output wire [6:0] scan_in_inst_27_data_3,
output wire [6:0] scan_in_inst_28_data_3,
output wire [6:0] scan_in_inst_29_data_3,
output wire [6:0] scan_in_inst_30_data_3,
output wire [6:0] scan_in_inst_31_data_3,
output wire scan_in_inst_req_3,
input wire scan_in_inst_ack_3,
output wire [1:0] scan_in_inst_cmd_3,
output wire i2c_req,
input wire i2c_ack,
output wire [6:0] i2c_slave_address,
output wire [1:0] i2c_burst_count_wr,
output wire [1:0] i2c_burst_count_rd,
output wire [7:0] i2c_wdata0,
output wire [7:0] i2c_wdata1,
output wire [7:0] i2c_wdata2,
output wire [7:0] i2c_wdata3,
output wire i2c_rd_wrn,
input wire i2c_nack,
input wire [7:0] i2c_rdata0,
input wire [7:0] i2c_rdata1,
input wire [7:0] i2c_rdata2,
input wire [7:0] i2c_rdata3
);

/*************************************************/
/* Define Memory and Connect to Flattened Vector */
/*************************************************/
wire [2047:0] flat_ssp1_controller_uart_write_mem;
generate for (genvar i=0; i<256; i=i+1) begin: gen_write_ssp1_controller_uart
    assign flat_ssp1_controller_uart_write_mem[((i+1)*8)-1-:8] = ssp1_controller_uart_write_mem[i];
end endgenerate
wire [2047:0] flat_ssp1_controller_uart_read_mem;
generate for (genvar i=0; i<256; i=i+1) begin: gen_read_ssp1_controller_uart
    assign ssp1_controller_uart_read_mem[i] = flat_ssp1_controller_uart_read_mem[((i+1)*8)-1-:8];
end endgenerate

/****************/
/* Field: RESET */
/****************/
// Assigns for register: reset
assign flat_ssp1_controller_uart_read_mem[`reset_Sel] = reset;
assign reset = flat_ssp1_controller_uart_write_mem[`reset_Sel];

/***************/
/* Field: USER */
/***************/
// Assigns for register: leds
assign flat_ssp1_controller_uart_read_mem[`leds_Sel] = leds;
assign leds = flat_ssp1_controller_uart_write_mem[`leds_Sel];
// Assigns for register: shifter_oe_n
assign flat_ssp1_controller_uart_read_mem[`shifter_oe_n_Sel] = shifter_oe_n;
assign shifter_oe_n = flat_ssp1_controller_uart_write_mem[`shifter_oe_n_Sel];
// Assigns for register: scan_cg_en
assign flat_ssp1_controller_uart_read_mem[`scan_cg_en_Sel] = scan_cg_en;
assign scan_cg_en = flat_ssp1_controller_uart_write_mem[`scan_cg_en_Sel];

/*******************/
/* Field: LOOPBACK */
/*******************/
// Assigns for register: loopback_so_data_0
assign flat_ssp1_controller_uart_read_mem[`loopback_so_data_0_Sel] = loopback_so_data_0;
// Assigns for register: loopback_so_data_1
assign flat_ssp1_controller_uart_read_mem[`loopback_so_data_1_Sel] = loopback_so_data_1;
// Assigns for register: loopback_so_data_2
assign flat_ssp1_controller_uart_read_mem[`loopback_so_data_2_Sel] = loopback_so_data_2;
// Assigns for register: loopback_so_data_3
assign flat_ssp1_controller_uart_read_mem[`loopback_so_data_3_Sel] = loopback_so_data_3;

/********************/
/* Field: ADDRESS_0 */
/********************/
// Assigns for register: scan_in_addr_address_0_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_0_r0_Sel] = scan_in_addr_address_0_r0;
assign scan_in_addr_address_0_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_0_r0_Sel];
// Assigns for register: scan_in_addr_lb_sel_0_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_0_r0_Sel] = scan_in_addr_lb_sel_0_r0;
assign scan_in_addr_lb_sel_0_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_0_r0_Sel];
// Assigns for register: scan_in_addr_enable_0_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_0_r0_Sel] = scan_in_addr_enable_0_r0;
assign scan_in_addr_enable_0_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_0_r0_Sel];
// Assigns for register: scan_in_addr_address_0_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_0_r1_Sel] = scan_in_addr_address_0_r1;
assign scan_in_addr_address_0_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_0_r1_Sel];
// Assigns for register: scan_in_addr_lb_sel_0_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_0_r1_Sel] = scan_in_addr_lb_sel_0_r1;
assign scan_in_addr_lb_sel_0_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_0_r1_Sel];
// Assigns for register: scan_in_addr_enable_0_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_0_r1_Sel] = scan_in_addr_enable_0_r1;
assign scan_in_addr_enable_0_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_0_r1_Sel];
// Assigns for register: scan_in_addr_address_0_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_0_r2_Sel] = scan_in_addr_address_0_r2;
assign scan_in_addr_address_0_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_0_r2_Sel];
// Assigns for register: scan_in_addr_lb_sel_0_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_0_r2_Sel] = scan_in_addr_lb_sel_0_r2;
assign scan_in_addr_lb_sel_0_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_0_r2_Sel];
// Assigns for register: scan_in_addr_enable_0_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_0_r2_Sel] = scan_in_addr_enable_0_r2;
assign scan_in_addr_enable_0_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_0_r2_Sel];
// Assigns for register: scan_in_addr_address_0_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_0_r3_Sel] = scan_in_addr_address_0_r3;
assign scan_in_addr_address_0_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_0_r3_Sel];
// Assigns for register: scan_in_addr_lb_sel_0_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_0_r3_Sel] = scan_in_addr_lb_sel_0_r3;
assign scan_in_addr_lb_sel_0_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_0_r3_Sel];
// Assigns for register: scan_in_addr_enable_0_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_0_r3_Sel] = scan_in_addr_enable_0_r3;
assign scan_in_addr_enable_0_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_0_r3_Sel];
// Assigns for register: scan_in_addr_req_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_req_0_Sel] = scan_in_addr_req_0;
assign scan_in_addr_req_0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_req_0_Sel];
// Assigns for register: scan_in_addr_cmd_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_cmd_0_Sel] = scan_in_addr_cmd_0;
assign scan_in_addr_cmd_0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_cmd_0_Sel];
// Assigns for register: scan_in_addr_ack_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_ack_0_Sel] = scan_in_addr_ack_0;

/********************/
/* Field: ADDRESS_1 */
/********************/
// Assigns for register: scan_in_addr_address_1_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_1_r0_Sel] = scan_in_addr_address_1_r0;
assign scan_in_addr_address_1_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_1_r0_Sel];
// Assigns for register: scan_in_addr_lb_sel_1_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_1_r0_Sel] = scan_in_addr_lb_sel_1_r0;
assign scan_in_addr_lb_sel_1_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_1_r0_Sel];
// Assigns for register: scan_in_addr_enable_1_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_1_r0_Sel] = scan_in_addr_enable_1_r0;
assign scan_in_addr_enable_1_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_1_r0_Sel];
// Assigns for register: scan_in_addr_address_1_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_1_r1_Sel] = scan_in_addr_address_1_r1;
assign scan_in_addr_address_1_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_1_r1_Sel];
// Assigns for register: scan_in_addr_lb_sel_1_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_1_r1_Sel] = scan_in_addr_lb_sel_1_r1;
assign scan_in_addr_lb_sel_1_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_1_r1_Sel];
// Assigns for register: scan_in_addr_enable_1_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_1_r1_Sel] = scan_in_addr_enable_1_r1;
assign scan_in_addr_enable_1_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_1_r1_Sel];
// Assigns for register: scan_in_addr_address_1_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_1_r2_Sel] = scan_in_addr_address_1_r2;
assign scan_in_addr_address_1_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_1_r2_Sel];
// Assigns for register: scan_in_addr_lb_sel_1_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_1_r2_Sel] = scan_in_addr_lb_sel_1_r2;
assign scan_in_addr_lb_sel_1_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_1_r2_Sel];
// Assigns for register: scan_in_addr_enable_1_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_1_r2_Sel] = scan_in_addr_enable_1_r2;
assign scan_in_addr_enable_1_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_1_r2_Sel];
// Assigns for register: scan_in_addr_address_1_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_1_r3_Sel] = scan_in_addr_address_1_r3;
assign scan_in_addr_address_1_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_1_r3_Sel];
// Assigns for register: scan_in_addr_lb_sel_1_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_1_r3_Sel] = scan_in_addr_lb_sel_1_r3;
assign scan_in_addr_lb_sel_1_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_1_r3_Sel];
// Assigns for register: scan_in_addr_enable_1_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_1_r3_Sel] = scan_in_addr_enable_1_r3;
assign scan_in_addr_enable_1_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_1_r3_Sel];
// Assigns for register: scan_in_addr_req_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_req_1_Sel] = scan_in_addr_req_1;
assign scan_in_addr_req_1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_req_1_Sel];
// Assigns for register: scan_in_addr_cmd_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_cmd_1_Sel] = scan_in_addr_cmd_1;
assign scan_in_addr_cmd_1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_cmd_1_Sel];
// Assigns for register: scan_in_addr_ack_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_ack_1_Sel] = scan_in_addr_ack_1;

/********************/
/* Field: ADDRESS_2 */
/********************/
// Assigns for register: scan_in_addr_address_2_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_2_r0_Sel] = scan_in_addr_address_2_r0;
assign scan_in_addr_address_2_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_2_r0_Sel];
// Assigns for register: scan_in_addr_lb_sel_2_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_2_r0_Sel] = scan_in_addr_lb_sel_2_r0;
assign scan_in_addr_lb_sel_2_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_2_r0_Sel];
// Assigns for register: scan_in_addr_enable_2_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_2_r0_Sel] = scan_in_addr_enable_2_r0;
assign scan_in_addr_enable_2_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_2_r0_Sel];
// Assigns for register: scan_in_addr_address_2_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_2_r1_Sel] = scan_in_addr_address_2_r1;
assign scan_in_addr_address_2_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_2_r1_Sel];
// Assigns for register: scan_in_addr_lb_sel_2_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_2_r1_Sel] = scan_in_addr_lb_sel_2_r1;
assign scan_in_addr_lb_sel_2_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_2_r1_Sel];
// Assigns for register: scan_in_addr_enable_2_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_2_r1_Sel] = scan_in_addr_enable_2_r1;
assign scan_in_addr_enable_2_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_2_r1_Sel];
// Assigns for register: scan_in_addr_address_2_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_2_r2_Sel] = scan_in_addr_address_2_r2;
assign scan_in_addr_address_2_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_2_r2_Sel];
// Assigns for register: scan_in_addr_lb_sel_2_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_2_r2_Sel] = scan_in_addr_lb_sel_2_r2;
assign scan_in_addr_lb_sel_2_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_2_r2_Sel];
// Assigns for register: scan_in_addr_enable_2_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_2_r2_Sel] = scan_in_addr_enable_2_r2;
assign scan_in_addr_enable_2_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_2_r2_Sel];
// Assigns for register: scan_in_addr_address_2_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_2_r3_Sel] = scan_in_addr_address_2_r3;
assign scan_in_addr_address_2_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_2_r3_Sel];
// Assigns for register: scan_in_addr_lb_sel_2_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_2_r3_Sel] = scan_in_addr_lb_sel_2_r3;
assign scan_in_addr_lb_sel_2_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_2_r3_Sel];
// Assigns for register: scan_in_addr_enable_2_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_2_r3_Sel] = scan_in_addr_enable_2_r3;
assign scan_in_addr_enable_2_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_2_r3_Sel];
// Assigns for register: scan_in_addr_req_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_req_2_Sel] = scan_in_addr_req_2;
assign scan_in_addr_req_2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_req_2_Sel];
// Assigns for register: scan_in_addr_cmd_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_cmd_2_Sel] = scan_in_addr_cmd_2;
assign scan_in_addr_cmd_2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_cmd_2_Sel];
// Assigns for register: scan_in_addr_ack_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_ack_2_Sel] = scan_in_addr_ack_2;

/********************/
/* Field: ADDRESS_3 */
/********************/
// Assigns for register: scan_in_addr_address_3_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_3_r0_Sel] = scan_in_addr_address_3_r0;
assign scan_in_addr_address_3_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_3_r0_Sel];
// Assigns for register: scan_in_addr_lb_sel_3_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_3_r0_Sel] = scan_in_addr_lb_sel_3_r0;
assign scan_in_addr_lb_sel_3_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_3_r0_Sel];
// Assigns for register: scan_in_addr_enable_3_r0
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_3_r0_Sel] = scan_in_addr_enable_3_r0;
assign scan_in_addr_enable_3_r0 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_3_r0_Sel];
// Assigns for register: scan_in_addr_address_3_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_3_r1_Sel] = scan_in_addr_address_3_r1;
assign scan_in_addr_address_3_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_3_r1_Sel];
// Assigns for register: scan_in_addr_lb_sel_3_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_3_r1_Sel] = scan_in_addr_lb_sel_3_r1;
assign scan_in_addr_lb_sel_3_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_3_r1_Sel];
// Assigns for register: scan_in_addr_enable_3_r1
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_3_r1_Sel] = scan_in_addr_enable_3_r1;
assign scan_in_addr_enable_3_r1 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_3_r1_Sel];
// Assigns for register: scan_in_addr_address_3_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_3_r2_Sel] = scan_in_addr_address_3_r2;
assign scan_in_addr_address_3_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_3_r2_Sel];
// Assigns for register: scan_in_addr_lb_sel_3_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_3_r2_Sel] = scan_in_addr_lb_sel_3_r2;
assign scan_in_addr_lb_sel_3_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_3_r2_Sel];
// Assigns for register: scan_in_addr_enable_3_r2
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_3_r2_Sel] = scan_in_addr_enable_3_r2;
assign scan_in_addr_enable_3_r2 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_3_r2_Sel];
// Assigns for register: scan_in_addr_address_3_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_address_3_r3_Sel] = scan_in_addr_address_3_r3;
assign scan_in_addr_address_3_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_address_3_r3_Sel];
// Assigns for register: scan_in_addr_lb_sel_3_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_lb_sel_3_r3_Sel] = scan_in_addr_lb_sel_3_r3;
assign scan_in_addr_lb_sel_3_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_lb_sel_3_r3_Sel];
// Assigns for register: scan_in_addr_enable_3_r3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_enable_3_r3_Sel] = scan_in_addr_enable_3_r3;
assign scan_in_addr_enable_3_r3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_enable_3_r3_Sel];
// Assigns for register: scan_in_addr_req_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_req_3_Sel] = scan_in_addr_req_3;
assign scan_in_addr_req_3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_req_3_Sel];
// Assigns for register: scan_in_addr_cmd_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_cmd_3_Sel] = scan_in_addr_cmd_3;
assign scan_in_addr_cmd_3 = flat_ssp1_controller_uart_write_mem[`scan_in_addr_cmd_3_Sel];
// Assigns for register: scan_in_addr_ack_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_addr_ack_3_Sel] = scan_in_addr_ack_3;

/************************/
/* Field: INSTRUCTION_0 */
/************************/
// Assigns for register: scan_in_inst_0_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_0_data_0_Sel] = scan_in_inst_0_data_0;
assign scan_in_inst_0_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_0_data_0_Sel];
// Assigns for register: scan_in_inst_1_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_1_data_0_Sel] = scan_in_inst_1_data_0;
assign scan_in_inst_1_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_1_data_0_Sel];
// Assigns for register: scan_in_inst_2_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_2_data_0_Sel] = scan_in_inst_2_data_0;
assign scan_in_inst_2_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_2_data_0_Sel];
// Assigns for register: scan_in_inst_3_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_3_data_0_Sel] = scan_in_inst_3_data_0;
assign scan_in_inst_3_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_3_data_0_Sel];
// Assigns for register: scan_in_inst_4_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_4_data_0_Sel] = scan_in_inst_4_data_0;
assign scan_in_inst_4_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_4_data_0_Sel];
// Assigns for register: scan_in_inst_5_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_5_data_0_Sel] = scan_in_inst_5_data_0;
assign scan_in_inst_5_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_5_data_0_Sel];
// Assigns for register: scan_in_inst_6_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_6_data_0_Sel] = scan_in_inst_6_data_0;
assign scan_in_inst_6_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_6_data_0_Sel];
// Assigns for register: scan_in_inst_7_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_7_data_0_Sel] = scan_in_inst_7_data_0;
assign scan_in_inst_7_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_7_data_0_Sel];
// Assigns for register: scan_in_inst_8_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_8_data_0_Sel] = scan_in_inst_8_data_0;
assign scan_in_inst_8_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_8_data_0_Sel];
// Assigns for register: scan_in_inst_9_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_9_data_0_Sel] = scan_in_inst_9_data_0;
assign scan_in_inst_9_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_9_data_0_Sel];
// Assigns for register: scan_in_inst_10_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_10_data_0_Sel] = scan_in_inst_10_data_0;
assign scan_in_inst_10_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_10_data_0_Sel];
// Assigns for register: scan_in_inst_11_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_11_data_0_Sel] = scan_in_inst_11_data_0;
assign scan_in_inst_11_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_11_data_0_Sel];
// Assigns for register: scan_in_inst_12_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_12_data_0_Sel] = scan_in_inst_12_data_0;
assign scan_in_inst_12_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_12_data_0_Sel];
// Assigns for register: scan_in_inst_13_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_13_data_0_Sel] = scan_in_inst_13_data_0;
assign scan_in_inst_13_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_13_data_0_Sel];
// Assigns for register: scan_in_inst_14_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_14_data_0_Sel] = scan_in_inst_14_data_0;
assign scan_in_inst_14_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_14_data_0_Sel];
// Assigns for register: scan_in_inst_15_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_15_data_0_Sel] = scan_in_inst_15_data_0;
assign scan_in_inst_15_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_15_data_0_Sel];
// Assigns for register: scan_in_inst_16_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_16_data_0_Sel] = scan_in_inst_16_data_0;
assign scan_in_inst_16_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_16_data_0_Sel];
// Assigns for register: scan_in_inst_17_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_17_data_0_Sel] = scan_in_inst_17_data_0;
assign scan_in_inst_17_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_17_data_0_Sel];
// Assigns for register: scan_in_inst_18_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_18_data_0_Sel] = scan_in_inst_18_data_0;
assign scan_in_inst_18_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_18_data_0_Sel];
// Assigns for register: scan_in_inst_19_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_19_data_0_Sel] = scan_in_inst_19_data_0;
assign scan_in_inst_19_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_19_data_0_Sel];
// Assigns for register: scan_in_inst_20_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_20_data_0_Sel] = scan_in_inst_20_data_0;
assign scan_in_inst_20_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_20_data_0_Sel];
// Assigns for register: scan_in_inst_21_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_21_data_0_Sel] = scan_in_inst_21_data_0;
assign scan_in_inst_21_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_21_data_0_Sel];
// Assigns for register: scan_in_inst_22_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_22_data_0_Sel] = scan_in_inst_22_data_0;
assign scan_in_inst_22_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_22_data_0_Sel];
// Assigns for register: scan_in_inst_23_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_23_data_0_Sel] = scan_in_inst_23_data_0;
assign scan_in_inst_23_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_23_data_0_Sel];
// Assigns for register: scan_in_inst_24_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_24_data_0_Sel] = scan_in_inst_24_data_0;
assign scan_in_inst_24_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_24_data_0_Sel];
// Assigns for register: scan_in_inst_25_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_25_data_0_Sel] = scan_in_inst_25_data_0;
assign scan_in_inst_25_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_25_data_0_Sel];
// Assigns for register: scan_in_inst_26_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_26_data_0_Sel] = scan_in_inst_26_data_0;
assign scan_in_inst_26_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_26_data_0_Sel];
// Assigns for register: scan_in_inst_27_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_27_data_0_Sel] = scan_in_inst_27_data_0;
assign scan_in_inst_27_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_27_data_0_Sel];
// Assigns for register: scan_in_inst_28_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_28_data_0_Sel] = scan_in_inst_28_data_0;
assign scan_in_inst_28_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_28_data_0_Sel];
// Assigns for register: scan_in_inst_29_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_29_data_0_Sel] = scan_in_inst_29_data_0;
assign scan_in_inst_29_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_29_data_0_Sel];
// Assigns for register: scan_in_inst_30_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_30_data_0_Sel] = scan_in_inst_30_data_0;
assign scan_in_inst_30_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_30_data_0_Sel];
// Assigns for register: scan_in_inst_31_data_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_31_data_0_Sel] = scan_in_inst_31_data_0;
assign scan_in_inst_31_data_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_31_data_0_Sel];
// Assigns for register: scan_in_inst_req_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_req_0_Sel] = scan_in_inst_req_0;
assign scan_in_inst_req_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_req_0_Sel];
// Assigns for register: scan_in_inst_cmd_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_cmd_0_Sel] = scan_in_inst_cmd_0;
assign scan_in_inst_cmd_0 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_cmd_0_Sel];
// Assigns for register: scan_in_inst_ack_0
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_ack_0_Sel] = scan_in_inst_ack_0;

/************************/
/* Field: INSTRUCTION_1 */
/************************/
// Assigns for register: scan_in_inst_0_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_0_data_1_Sel] = scan_in_inst_0_data_1;
assign scan_in_inst_0_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_0_data_1_Sel];
// Assigns for register: scan_in_inst_1_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_1_data_1_Sel] = scan_in_inst_1_data_1;
assign scan_in_inst_1_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_1_data_1_Sel];
// Assigns for register: scan_in_inst_2_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_2_data_1_Sel] = scan_in_inst_2_data_1;
assign scan_in_inst_2_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_2_data_1_Sel];
// Assigns for register: scan_in_inst_3_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_3_data_1_Sel] = scan_in_inst_3_data_1;
assign scan_in_inst_3_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_3_data_1_Sel];
// Assigns for register: scan_in_inst_4_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_4_data_1_Sel] = scan_in_inst_4_data_1;
assign scan_in_inst_4_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_4_data_1_Sel];
// Assigns for register: scan_in_inst_5_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_5_data_1_Sel] = scan_in_inst_5_data_1;
assign scan_in_inst_5_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_5_data_1_Sel];
// Assigns for register: scan_in_inst_6_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_6_data_1_Sel] = scan_in_inst_6_data_1;
assign scan_in_inst_6_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_6_data_1_Sel];
// Assigns for register: scan_in_inst_7_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_7_data_1_Sel] = scan_in_inst_7_data_1;
assign scan_in_inst_7_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_7_data_1_Sel];
// Assigns for register: scan_in_inst_8_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_8_data_1_Sel] = scan_in_inst_8_data_1;
assign scan_in_inst_8_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_8_data_1_Sel];
// Assigns for register: scan_in_inst_9_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_9_data_1_Sel] = scan_in_inst_9_data_1;
assign scan_in_inst_9_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_9_data_1_Sel];
// Assigns for register: scan_in_inst_10_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_10_data_1_Sel] = scan_in_inst_10_data_1;
assign scan_in_inst_10_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_10_data_1_Sel];
// Assigns for register: scan_in_inst_11_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_11_data_1_Sel] = scan_in_inst_11_data_1;
assign scan_in_inst_11_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_11_data_1_Sel];
// Assigns for register: scan_in_inst_12_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_12_data_1_Sel] = scan_in_inst_12_data_1;
assign scan_in_inst_12_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_12_data_1_Sel];
// Assigns for register: scan_in_inst_13_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_13_data_1_Sel] = scan_in_inst_13_data_1;
assign scan_in_inst_13_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_13_data_1_Sel];
// Assigns for register: scan_in_inst_14_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_14_data_1_Sel] = scan_in_inst_14_data_1;
assign scan_in_inst_14_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_14_data_1_Sel];
// Assigns for register: scan_in_inst_15_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_15_data_1_Sel] = scan_in_inst_15_data_1;
assign scan_in_inst_15_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_15_data_1_Sel];
// Assigns for register: scan_in_inst_16_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_16_data_1_Sel] = scan_in_inst_16_data_1;
assign scan_in_inst_16_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_16_data_1_Sel];
// Assigns for register: scan_in_inst_17_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_17_data_1_Sel] = scan_in_inst_17_data_1;
assign scan_in_inst_17_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_17_data_1_Sel];
// Assigns for register: scan_in_inst_18_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_18_data_1_Sel] = scan_in_inst_18_data_1;
assign scan_in_inst_18_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_18_data_1_Sel];
// Assigns for register: scan_in_inst_19_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_19_data_1_Sel] = scan_in_inst_19_data_1;
assign scan_in_inst_19_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_19_data_1_Sel];
// Assigns for register: scan_in_inst_20_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_20_data_1_Sel] = scan_in_inst_20_data_1;
assign scan_in_inst_20_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_20_data_1_Sel];
// Assigns for register: scan_in_inst_21_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_21_data_1_Sel] = scan_in_inst_21_data_1;
assign scan_in_inst_21_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_21_data_1_Sel];
// Assigns for register: scan_in_inst_22_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_22_data_1_Sel] = scan_in_inst_22_data_1;
assign scan_in_inst_22_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_22_data_1_Sel];
// Assigns for register: scan_in_inst_23_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_23_data_1_Sel] = scan_in_inst_23_data_1;
assign scan_in_inst_23_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_23_data_1_Sel];
// Assigns for register: scan_in_inst_24_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_24_data_1_Sel] = scan_in_inst_24_data_1;
assign scan_in_inst_24_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_24_data_1_Sel];
// Assigns for register: scan_in_inst_25_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_25_data_1_Sel] = scan_in_inst_25_data_1;
assign scan_in_inst_25_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_25_data_1_Sel];
// Assigns for register: scan_in_inst_26_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_26_data_1_Sel] = scan_in_inst_26_data_1;
assign scan_in_inst_26_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_26_data_1_Sel];
// Assigns for register: scan_in_inst_27_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_27_data_1_Sel] = scan_in_inst_27_data_1;
assign scan_in_inst_27_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_27_data_1_Sel];
// Assigns for register: scan_in_inst_28_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_28_data_1_Sel] = scan_in_inst_28_data_1;
assign scan_in_inst_28_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_28_data_1_Sel];
// Assigns for register: scan_in_inst_29_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_29_data_1_Sel] = scan_in_inst_29_data_1;
assign scan_in_inst_29_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_29_data_1_Sel];
// Assigns for register: scan_in_inst_30_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_30_data_1_Sel] = scan_in_inst_30_data_1;
assign scan_in_inst_30_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_30_data_1_Sel];
// Assigns for register: scan_in_inst_31_data_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_31_data_1_Sel] = scan_in_inst_31_data_1;
assign scan_in_inst_31_data_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_31_data_1_Sel];
// Assigns for register: scan_in_inst_req_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_req_1_Sel] = scan_in_inst_req_1;
assign scan_in_inst_req_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_req_1_Sel];
// Assigns for register: scan_in_inst_cmd_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_cmd_1_Sel] = scan_in_inst_cmd_1;
assign scan_in_inst_cmd_1 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_cmd_1_Sel];
// Assigns for register: scan_in_inst_ack_1
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_ack_1_Sel] = scan_in_inst_ack_1;

/************************/
/* Field: INSTRUCTION_2 */
/************************/
// Assigns for register: scan_in_inst_0_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_0_data_2_Sel] = scan_in_inst_0_data_2;
assign scan_in_inst_0_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_0_data_2_Sel];
// Assigns for register: scan_in_inst_1_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_1_data_2_Sel] = scan_in_inst_1_data_2;
assign scan_in_inst_1_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_1_data_2_Sel];
// Assigns for register: scan_in_inst_2_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_2_data_2_Sel] = scan_in_inst_2_data_2;
assign scan_in_inst_2_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_2_data_2_Sel];
// Assigns for register: scan_in_inst_3_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_3_data_2_Sel] = scan_in_inst_3_data_2;
assign scan_in_inst_3_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_3_data_2_Sel];
// Assigns for register: scan_in_inst_4_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_4_data_2_Sel] = scan_in_inst_4_data_2;
assign scan_in_inst_4_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_4_data_2_Sel];
// Assigns for register: scan_in_inst_5_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_5_data_2_Sel] = scan_in_inst_5_data_2;
assign scan_in_inst_5_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_5_data_2_Sel];
// Assigns for register: scan_in_inst_6_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_6_data_2_Sel] = scan_in_inst_6_data_2;
assign scan_in_inst_6_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_6_data_2_Sel];
// Assigns for register: scan_in_inst_7_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_7_data_2_Sel] = scan_in_inst_7_data_2;
assign scan_in_inst_7_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_7_data_2_Sel];
// Assigns for register: scan_in_inst_8_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_8_data_2_Sel] = scan_in_inst_8_data_2;
assign scan_in_inst_8_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_8_data_2_Sel];
// Assigns for register: scan_in_inst_9_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_9_data_2_Sel] = scan_in_inst_9_data_2;
assign scan_in_inst_9_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_9_data_2_Sel];
// Assigns for register: scan_in_inst_10_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_10_data_2_Sel] = scan_in_inst_10_data_2;
assign scan_in_inst_10_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_10_data_2_Sel];
// Assigns for register: scan_in_inst_11_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_11_data_2_Sel] = scan_in_inst_11_data_2;
assign scan_in_inst_11_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_11_data_2_Sel];
// Assigns for register: scan_in_inst_12_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_12_data_2_Sel] = scan_in_inst_12_data_2;
assign scan_in_inst_12_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_12_data_2_Sel];
// Assigns for register: scan_in_inst_13_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_13_data_2_Sel] = scan_in_inst_13_data_2;
assign scan_in_inst_13_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_13_data_2_Sel];
// Assigns for register: scan_in_inst_14_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_14_data_2_Sel] = scan_in_inst_14_data_2;
assign scan_in_inst_14_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_14_data_2_Sel];
// Assigns for register: scan_in_inst_15_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_15_data_2_Sel] = scan_in_inst_15_data_2;
assign scan_in_inst_15_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_15_data_2_Sel];
// Assigns for register: scan_in_inst_16_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_16_data_2_Sel] = scan_in_inst_16_data_2;
assign scan_in_inst_16_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_16_data_2_Sel];
// Assigns for register: scan_in_inst_17_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_17_data_2_Sel] = scan_in_inst_17_data_2;
assign scan_in_inst_17_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_17_data_2_Sel];
// Assigns for register: scan_in_inst_18_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_18_data_2_Sel] = scan_in_inst_18_data_2;
assign scan_in_inst_18_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_18_data_2_Sel];
// Assigns for register: scan_in_inst_19_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_19_data_2_Sel] = scan_in_inst_19_data_2;
assign scan_in_inst_19_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_19_data_2_Sel];
// Assigns for register: scan_in_inst_20_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_20_data_2_Sel] = scan_in_inst_20_data_2;
assign scan_in_inst_20_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_20_data_2_Sel];
// Assigns for register: scan_in_inst_21_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_21_data_2_Sel] = scan_in_inst_21_data_2;
assign scan_in_inst_21_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_21_data_2_Sel];
// Assigns for register: scan_in_inst_22_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_22_data_2_Sel] = scan_in_inst_22_data_2;
assign scan_in_inst_22_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_22_data_2_Sel];
// Assigns for register: scan_in_inst_23_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_23_data_2_Sel] = scan_in_inst_23_data_2;
assign scan_in_inst_23_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_23_data_2_Sel];
// Assigns for register: scan_in_inst_24_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_24_data_2_Sel] = scan_in_inst_24_data_2;
assign scan_in_inst_24_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_24_data_2_Sel];
// Assigns for register: scan_in_inst_25_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_25_data_2_Sel] = scan_in_inst_25_data_2;
assign scan_in_inst_25_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_25_data_2_Sel];
// Assigns for register: scan_in_inst_26_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_26_data_2_Sel] = scan_in_inst_26_data_2;
assign scan_in_inst_26_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_26_data_2_Sel];
// Assigns for register: scan_in_inst_27_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_27_data_2_Sel] = scan_in_inst_27_data_2;
assign scan_in_inst_27_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_27_data_2_Sel];
// Assigns for register: scan_in_inst_28_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_28_data_2_Sel] = scan_in_inst_28_data_2;
assign scan_in_inst_28_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_28_data_2_Sel];
// Assigns for register: scan_in_inst_29_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_29_data_2_Sel] = scan_in_inst_29_data_2;
assign scan_in_inst_29_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_29_data_2_Sel];
// Assigns for register: scan_in_inst_30_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_30_data_2_Sel] = scan_in_inst_30_data_2;
assign scan_in_inst_30_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_30_data_2_Sel];
// Assigns for register: scan_in_inst_31_data_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_31_data_2_Sel] = scan_in_inst_31_data_2;
assign scan_in_inst_31_data_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_31_data_2_Sel];
// Assigns for register: scan_in_inst_req_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_req_2_Sel] = scan_in_inst_req_2;
assign scan_in_inst_req_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_req_2_Sel];
// Assigns for register: scan_in_inst_cmd_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_cmd_2_Sel] = scan_in_inst_cmd_2;
assign scan_in_inst_cmd_2 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_cmd_2_Sel];
// Assigns for register: scan_in_inst_ack_2
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_ack_2_Sel] = scan_in_inst_ack_2;

/************************/
/* Field: INSTRUCTION_3 */
/************************/
// Assigns for register: scan_in_inst_0_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_0_data_3_Sel] = scan_in_inst_0_data_3;
assign scan_in_inst_0_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_0_data_3_Sel];
// Assigns for register: scan_in_inst_1_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_1_data_3_Sel] = scan_in_inst_1_data_3;
assign scan_in_inst_1_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_1_data_3_Sel];
// Assigns for register: scan_in_inst_2_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_2_data_3_Sel] = scan_in_inst_2_data_3;
assign scan_in_inst_2_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_2_data_3_Sel];
// Assigns for register: scan_in_inst_3_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_3_data_3_Sel] = scan_in_inst_3_data_3;
assign scan_in_inst_3_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_3_data_3_Sel];
// Assigns for register: scan_in_inst_4_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_4_data_3_Sel] = scan_in_inst_4_data_3;
assign scan_in_inst_4_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_4_data_3_Sel];
// Assigns for register: scan_in_inst_5_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_5_data_3_Sel] = scan_in_inst_5_data_3;
assign scan_in_inst_5_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_5_data_3_Sel];
// Assigns for register: scan_in_inst_6_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_6_data_3_Sel] = scan_in_inst_6_data_3;
assign scan_in_inst_6_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_6_data_3_Sel];
// Assigns for register: scan_in_inst_7_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_7_data_3_Sel] = scan_in_inst_7_data_3;
assign scan_in_inst_7_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_7_data_3_Sel];
// Assigns for register: scan_in_inst_8_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_8_data_3_Sel] = scan_in_inst_8_data_3;
assign scan_in_inst_8_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_8_data_3_Sel];
// Assigns for register: scan_in_inst_9_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_9_data_3_Sel] = scan_in_inst_9_data_3;
assign scan_in_inst_9_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_9_data_3_Sel];
// Assigns for register: scan_in_inst_10_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_10_data_3_Sel] = scan_in_inst_10_data_3;
assign scan_in_inst_10_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_10_data_3_Sel];
// Assigns for register: scan_in_inst_11_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_11_data_3_Sel] = scan_in_inst_11_data_3;
assign scan_in_inst_11_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_11_data_3_Sel];
// Assigns for register: scan_in_inst_12_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_12_data_3_Sel] = scan_in_inst_12_data_3;
assign scan_in_inst_12_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_12_data_3_Sel];
// Assigns for register: scan_in_inst_13_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_13_data_3_Sel] = scan_in_inst_13_data_3;
assign scan_in_inst_13_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_13_data_3_Sel];
// Assigns for register: scan_in_inst_14_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_14_data_3_Sel] = scan_in_inst_14_data_3;
assign scan_in_inst_14_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_14_data_3_Sel];
// Assigns for register: scan_in_inst_15_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_15_data_3_Sel] = scan_in_inst_15_data_3;
assign scan_in_inst_15_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_15_data_3_Sel];
// Assigns for register: scan_in_inst_16_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_16_data_3_Sel] = scan_in_inst_16_data_3;
assign scan_in_inst_16_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_16_data_3_Sel];
// Assigns for register: scan_in_inst_17_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_17_data_3_Sel] = scan_in_inst_17_data_3;
assign scan_in_inst_17_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_17_data_3_Sel];
// Assigns for register: scan_in_inst_18_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_18_data_3_Sel] = scan_in_inst_18_data_3;
assign scan_in_inst_18_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_18_data_3_Sel];
// Assigns for register: scan_in_inst_19_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_19_data_3_Sel] = scan_in_inst_19_data_3;
assign scan_in_inst_19_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_19_data_3_Sel];
// Assigns for register: scan_in_inst_20_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_20_data_3_Sel] = scan_in_inst_20_data_3;
assign scan_in_inst_20_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_20_data_3_Sel];
// Assigns for register: scan_in_inst_21_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_21_data_3_Sel] = scan_in_inst_21_data_3;
assign scan_in_inst_21_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_21_data_3_Sel];
// Assigns for register: scan_in_inst_22_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_22_data_3_Sel] = scan_in_inst_22_data_3;
assign scan_in_inst_22_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_22_data_3_Sel];
// Assigns for register: scan_in_inst_23_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_23_data_3_Sel] = scan_in_inst_23_data_3;
assign scan_in_inst_23_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_23_data_3_Sel];
// Assigns for register: scan_in_inst_24_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_24_data_3_Sel] = scan_in_inst_24_data_3;
assign scan_in_inst_24_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_24_data_3_Sel];
// Assigns for register: scan_in_inst_25_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_25_data_3_Sel] = scan_in_inst_25_data_3;
assign scan_in_inst_25_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_25_data_3_Sel];
// Assigns for register: scan_in_inst_26_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_26_data_3_Sel] = scan_in_inst_26_data_3;
assign scan_in_inst_26_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_26_data_3_Sel];
// Assigns for register: scan_in_inst_27_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_27_data_3_Sel] = scan_in_inst_27_data_3;
assign scan_in_inst_27_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_27_data_3_Sel];
// Assigns for register: scan_in_inst_28_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_28_data_3_Sel] = scan_in_inst_28_data_3;
assign scan_in_inst_28_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_28_data_3_Sel];
// Assigns for register: scan_in_inst_29_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_29_data_3_Sel] = scan_in_inst_29_data_3;
assign scan_in_inst_29_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_29_data_3_Sel];
// Assigns for register: scan_in_inst_30_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_30_data_3_Sel] = scan_in_inst_30_data_3;
assign scan_in_inst_30_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_30_data_3_Sel];
// Assigns for register: scan_in_inst_31_data_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_31_data_3_Sel] = scan_in_inst_31_data_3;
assign scan_in_inst_31_data_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_31_data_3_Sel];
// Assigns for register: scan_in_inst_req_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_req_3_Sel] = scan_in_inst_req_3;
assign scan_in_inst_req_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_req_3_Sel];
// Assigns for register: scan_in_inst_cmd_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_cmd_3_Sel] = scan_in_inst_cmd_3;
assign scan_in_inst_cmd_3 = flat_ssp1_controller_uart_write_mem[`scan_in_inst_cmd_3_Sel];
// Assigns for register: scan_in_inst_ack_3
assign flat_ssp1_controller_uart_read_mem[`scan_in_inst_ack_3_Sel] = scan_in_inst_ack_3;

/**************/
/* Field: I2C */
/**************/
// Assigns for register: i2c_req
assign flat_ssp1_controller_uart_read_mem[`i2c_req_Sel] = i2c_req;
assign i2c_req = flat_ssp1_controller_uart_write_mem[`i2c_req_Sel];
// Assigns for register: i2c_slave_address
assign flat_ssp1_controller_uart_read_mem[`i2c_slave_address_Sel] = i2c_slave_address;
assign i2c_slave_address = flat_ssp1_controller_uart_write_mem[`i2c_slave_address_Sel];
// Assigns for register: i2c_burst_count_wr
assign flat_ssp1_controller_uart_read_mem[`i2c_burst_count_wr_Sel] = i2c_burst_count_wr;
assign i2c_burst_count_wr = flat_ssp1_controller_uart_write_mem[`i2c_burst_count_wr_Sel];
// Assigns for register: i2c_burst_count_rd
assign flat_ssp1_controller_uart_read_mem[`i2c_burst_count_rd_Sel] = i2c_burst_count_rd;
assign i2c_burst_count_rd = flat_ssp1_controller_uart_write_mem[`i2c_burst_count_rd_Sel];
// Assigns for register: i2c_wdata0
assign flat_ssp1_controller_uart_read_mem[`i2c_wdata0_Sel] = i2c_wdata0;
assign i2c_wdata0 = flat_ssp1_controller_uart_write_mem[`i2c_wdata0_Sel];
// Assigns for register: i2c_wdata1
assign flat_ssp1_controller_uart_read_mem[`i2c_wdata1_Sel] = i2c_wdata1;
assign i2c_wdata1 = flat_ssp1_controller_uart_write_mem[`i2c_wdata1_Sel];
// Assigns for register: i2c_wdata2
assign flat_ssp1_controller_uart_read_mem[`i2c_wdata2_Sel] = i2c_wdata2;
assign i2c_wdata2 = flat_ssp1_controller_uart_write_mem[`i2c_wdata2_Sel];
// Assigns for register: i2c_wdata3
assign flat_ssp1_controller_uart_read_mem[`i2c_wdata3_Sel] = i2c_wdata3;
assign i2c_wdata3 = flat_ssp1_controller_uart_write_mem[`i2c_wdata3_Sel];
// Assigns for register: i2c_rd_wrn
assign flat_ssp1_controller_uart_read_mem[`i2c_rd_wrn_Sel] = i2c_rd_wrn;
assign i2c_rd_wrn = flat_ssp1_controller_uart_write_mem[`i2c_rd_wrn_Sel];
// Assigns for register: i2c_ack
assign flat_ssp1_controller_uart_read_mem[`i2c_ack_Sel] = i2c_ack;
// Assigns for register: i2c_nack
assign flat_ssp1_controller_uart_read_mem[`i2c_nack_Sel] = i2c_nack;
// Assigns for register: i2c_rdata0
assign flat_ssp1_controller_uart_read_mem[`i2c_rdata0_Sel] = i2c_rdata0;
// Assigns for register: i2c_rdata1
assign flat_ssp1_controller_uart_read_mem[`i2c_rdata1_Sel] = i2c_rdata1;
// Assigns for register: i2c_rdata2
assign flat_ssp1_controller_uart_read_mem[`i2c_rdata2_Sel] = i2c_rdata2;
// Assigns for register: i2c_rdata3
assign flat_ssp1_controller_uart_read_mem[`i2c_rdata3_Sel] = i2c_rdata3;
endmodule
`default_nettype wire