// File autogenerated by vlog_mem_map python project
// Date Generated: 2021-05-25 15:25:15.290170
// Configuration File: config.yml
// Memory Name: ssp1_controller_uart
// Memory Word Width: 8
// Address Range: 256

/****************/
/* Field: RESET */
/****************/
`define RESET_field_addr 0
// Defines for register "reset"
`define reset_LSbit 0
`define reset_MSbit 0
`define reset_Sel 0:0
`define reset_Width 1
`define reset_LSbit_Addr 0
`define reset_MSbit_Addr 0
`define reset_LSbit_Pos 0
`define reset_MSbit_Pos 0
// Field RESET length
`define RESET_field_bit_length 1
`define RESET_field_byte_length 1

/***************/
/* Field: USER */
/***************/
`define USER_field_addr 1
// Defines for register "leds"
`define leds_LSbit 8
`define leds_MSbit 15
`define leds_Sel 15:8
`define leds_Width 8
`define leds_LSbit_Addr 1
`define leds_MSbit_Addr 1
`define leds_LSbit_Pos 0
`define leds_MSbit_Pos 7
// Defines for register "shifter_oe_n"
`define shifter_oe_n_LSbit 16
`define shifter_oe_n_MSbit 16
`define shifter_oe_n_Sel 16:16
`define shifter_oe_n_Width 1
`define shifter_oe_n_LSbit_Addr 2
`define shifter_oe_n_MSbit_Addr 2
`define shifter_oe_n_LSbit_Pos 0
`define shifter_oe_n_MSbit_Pos 0
// Defines for register "scan_cg_en"
`define scan_cg_en_LSbit 17
`define scan_cg_en_MSbit 17
`define scan_cg_en_Sel 17:17
`define scan_cg_en_Width 1
`define scan_cg_en_LSbit_Addr 2
`define scan_cg_en_MSbit_Addr 2
`define scan_cg_en_LSbit_Pos 1
`define scan_cg_en_MSbit_Pos 1
// Field USER length
`define USER_field_bit_length 10
`define USER_field_byte_length 2

/*******************/
/* Field: LOOPBACK */
/*******************/
`define LOOPBACK_field_addr 3
// Defines for register "loopback_so_data_0"
`define loopback_so_data_0_LSbit 24
`define loopback_so_data_0_MSbit 51
`define loopback_so_data_0_Sel 51:24
`define loopback_so_data_0_Width 28
`define loopback_so_data_0_LSbit_Addr 3
`define loopback_so_data_0_MSbit_Addr 6
`define loopback_so_data_0_LSbit_Pos 0
`define loopback_so_data_0_MSbit_Pos 3
// Defines for register "loopback_so_data_1"
`define loopback_so_data_1_LSbit 52
`define loopback_so_data_1_MSbit 79
`define loopback_so_data_1_Sel 79:52
`define loopback_so_data_1_Width 28
`define loopback_so_data_1_LSbit_Addr 6
`define loopback_so_data_1_MSbit_Addr 9
`define loopback_so_data_1_LSbit_Pos 4
`define loopback_so_data_1_MSbit_Pos 7
// Defines for register "loopback_so_data_2"
`define loopback_so_data_2_LSbit 80
`define loopback_so_data_2_MSbit 107
`define loopback_so_data_2_Sel 107:80
`define loopback_so_data_2_Width 28
`define loopback_so_data_2_LSbit_Addr 10
`define loopback_so_data_2_MSbit_Addr 13
`define loopback_so_data_2_LSbit_Pos 0
`define loopback_so_data_2_MSbit_Pos 3
// Defines for register "loopback_so_data_3"
`define loopback_so_data_3_LSbit 108
`define loopback_so_data_3_MSbit 135
`define loopback_so_data_3_Sel 135:108
`define loopback_so_data_3_Width 28
`define loopback_so_data_3_LSbit_Addr 13
`define loopback_so_data_3_MSbit_Addr 16
`define loopback_so_data_3_LSbit_Pos 4
`define loopback_so_data_3_MSbit_Pos 7
// Field LOOPBACK length
`define LOOPBACK_field_bit_length 112
`define LOOPBACK_field_byte_length 14

/********************/
/* Field: ADDRESS_0 */
/********************/
`define ADDRESS_0_field_addr 17
// Defines for register "scan_in_addr_address_0_r0"
`define scan_in_addr_address_0_r0_LSbit 136
`define scan_in_addr_address_0_r0_MSbit 137
`define scan_in_addr_address_0_r0_Sel 137:136
`define scan_in_addr_address_0_r0_Width 2
`define scan_in_addr_address_0_r0_LSbit_Addr 17
`define scan_in_addr_address_0_r0_MSbit_Addr 17
`define scan_in_addr_address_0_r0_LSbit_Pos 0
`define scan_in_addr_address_0_r0_MSbit_Pos 1
// Defines for register "scan_in_addr_lb_sel_0_r0"
`define scan_in_addr_lb_sel_0_r0_LSbit 138
`define scan_in_addr_lb_sel_0_r0_MSbit 141
`define scan_in_addr_lb_sel_0_r0_Sel 141:138
`define scan_in_addr_lb_sel_0_r0_Width 4
`define scan_in_addr_lb_sel_0_r0_LSbit_Addr 17
`define scan_in_addr_lb_sel_0_r0_MSbit_Addr 17
`define scan_in_addr_lb_sel_0_r0_LSbit_Pos 2
`define scan_in_addr_lb_sel_0_r0_MSbit_Pos 5
// Defines for register "scan_in_addr_enable_0_r0"
`define scan_in_addr_enable_0_r0_LSbit 142
`define scan_in_addr_enable_0_r0_MSbit 142
`define scan_in_addr_enable_0_r0_Sel 142:142
`define scan_in_addr_enable_0_r0_Width 1
`define scan_in_addr_enable_0_r0_LSbit_Addr 17
`define scan_in_addr_enable_0_r0_MSbit_Addr 17
`define scan_in_addr_enable_0_r0_LSbit_Pos 6
`define scan_in_addr_enable_0_r0_MSbit_Pos 6
// Defines for register "scan_in_addr_address_0_r1"
`define scan_in_addr_address_0_r1_LSbit 143
`define scan_in_addr_address_0_r1_MSbit 144
`define scan_in_addr_address_0_r1_Sel 144:143
`define scan_in_addr_address_0_r1_Width 2
`define scan_in_addr_address_0_r1_LSbit_Addr 17
`define scan_in_addr_address_0_r1_MSbit_Addr 18
`define scan_in_addr_address_0_r1_LSbit_Pos 7
`define scan_in_addr_address_0_r1_MSbit_Pos 0
// Defines for register "scan_in_addr_lb_sel_0_r1"
`define scan_in_addr_lb_sel_0_r1_LSbit 145
`define scan_in_addr_lb_sel_0_r1_MSbit 148
`define scan_in_addr_lb_sel_0_r1_Sel 148:145
`define scan_in_addr_lb_sel_0_r1_Width 4
`define scan_in_addr_lb_sel_0_r1_LSbit_Addr 18
`define scan_in_addr_lb_sel_0_r1_MSbit_Addr 18
`define scan_in_addr_lb_sel_0_r1_LSbit_Pos 1
`define scan_in_addr_lb_sel_0_r1_MSbit_Pos 4
// Defines for register "scan_in_addr_enable_0_r1"
`define scan_in_addr_enable_0_r1_LSbit 149
`define scan_in_addr_enable_0_r1_MSbit 149
`define scan_in_addr_enable_0_r1_Sel 149:149
`define scan_in_addr_enable_0_r1_Width 1
`define scan_in_addr_enable_0_r1_LSbit_Addr 18
`define scan_in_addr_enable_0_r1_MSbit_Addr 18
`define scan_in_addr_enable_0_r1_LSbit_Pos 5
`define scan_in_addr_enable_0_r1_MSbit_Pos 5
// Defines for register "scan_in_addr_address_0_r2"
`define scan_in_addr_address_0_r2_LSbit 150
`define scan_in_addr_address_0_r2_MSbit 151
`define scan_in_addr_address_0_r2_Sel 151:150
`define scan_in_addr_address_0_r2_Width 2
`define scan_in_addr_address_0_r2_LSbit_Addr 18
`define scan_in_addr_address_0_r2_MSbit_Addr 18
`define scan_in_addr_address_0_r2_LSbit_Pos 6
`define scan_in_addr_address_0_r2_MSbit_Pos 7
// Defines for register "scan_in_addr_lb_sel_0_r2"
`define scan_in_addr_lb_sel_0_r2_LSbit 152
`define scan_in_addr_lb_sel_0_r2_MSbit 155
`define scan_in_addr_lb_sel_0_r2_Sel 155:152
`define scan_in_addr_lb_sel_0_r2_Width 4
`define scan_in_addr_lb_sel_0_r2_LSbit_Addr 19
`define scan_in_addr_lb_sel_0_r2_MSbit_Addr 19
`define scan_in_addr_lb_sel_0_r2_LSbit_Pos 0
`define scan_in_addr_lb_sel_0_r2_MSbit_Pos 3
// Defines for register "scan_in_addr_enable_0_r2"
`define scan_in_addr_enable_0_r2_LSbit 156
`define scan_in_addr_enable_0_r2_MSbit 156
`define scan_in_addr_enable_0_r2_Sel 156:156
`define scan_in_addr_enable_0_r2_Width 1
`define scan_in_addr_enable_0_r2_LSbit_Addr 19
`define scan_in_addr_enable_0_r2_MSbit_Addr 19
`define scan_in_addr_enable_0_r2_LSbit_Pos 4
`define scan_in_addr_enable_0_r2_MSbit_Pos 4
// Defines for register "scan_in_addr_address_0_r3"
`define scan_in_addr_address_0_r3_LSbit 157
`define scan_in_addr_address_0_r3_MSbit 158
`define scan_in_addr_address_0_r3_Sel 158:157
`define scan_in_addr_address_0_r3_Width 2
`define scan_in_addr_address_0_r3_LSbit_Addr 19
`define scan_in_addr_address_0_r3_MSbit_Addr 19
`define scan_in_addr_address_0_r3_LSbit_Pos 5
`define scan_in_addr_address_0_r3_MSbit_Pos 6
// Defines for register "scan_in_addr_lb_sel_0_r3"
`define scan_in_addr_lb_sel_0_r3_LSbit 159
`define scan_in_addr_lb_sel_0_r3_MSbit 162
`define scan_in_addr_lb_sel_0_r3_Sel 162:159
`define scan_in_addr_lb_sel_0_r3_Width 4
`define scan_in_addr_lb_sel_0_r3_LSbit_Addr 19
`define scan_in_addr_lb_sel_0_r3_MSbit_Addr 20
`define scan_in_addr_lb_sel_0_r3_LSbit_Pos 7
`define scan_in_addr_lb_sel_0_r3_MSbit_Pos 2
// Defines for register "scan_in_addr_enable_0_r3"
`define scan_in_addr_enable_0_r3_LSbit 163
`define scan_in_addr_enable_0_r3_MSbit 163
`define scan_in_addr_enable_0_r3_Sel 163:163
`define scan_in_addr_enable_0_r3_Width 1
`define scan_in_addr_enable_0_r3_LSbit_Addr 20
`define scan_in_addr_enable_0_r3_MSbit_Addr 20
`define scan_in_addr_enable_0_r3_LSbit_Pos 3
`define scan_in_addr_enable_0_r3_MSbit_Pos 3
// Defines for register "scan_in_addr_req_0"
`define scan_in_addr_req_0_LSbit 164
`define scan_in_addr_req_0_MSbit 164
`define scan_in_addr_req_0_Sel 164:164
`define scan_in_addr_req_0_Width 1
`define scan_in_addr_req_0_LSbit_Addr 20
`define scan_in_addr_req_0_MSbit_Addr 20
`define scan_in_addr_req_0_LSbit_Pos 4
`define scan_in_addr_req_0_MSbit_Pos 4
// Defines for register "scan_in_addr_cmd_0"
`define scan_in_addr_cmd_0_LSbit 165
`define scan_in_addr_cmd_0_MSbit 166
`define scan_in_addr_cmd_0_Sel 166:165
`define scan_in_addr_cmd_0_Width 2
`define scan_in_addr_cmd_0_LSbit_Addr 20
`define scan_in_addr_cmd_0_MSbit_Addr 20
`define scan_in_addr_cmd_0_LSbit_Pos 5
`define scan_in_addr_cmd_0_MSbit_Pos 6
// Defines for register "scan_in_addr_ack_0"
`define scan_in_addr_ack_0_LSbit 167
`define scan_in_addr_ack_0_MSbit 167
`define scan_in_addr_ack_0_Sel 167:167
`define scan_in_addr_ack_0_Width 1
`define scan_in_addr_ack_0_LSbit_Addr 20
`define scan_in_addr_ack_0_MSbit_Addr 20
`define scan_in_addr_ack_0_LSbit_Pos 7
`define scan_in_addr_ack_0_MSbit_Pos 7
// Field ADDRESS_0 length
`define ADDRESS_0_field_bit_length 32
`define ADDRESS_0_field_byte_length 4

/********************/
/* Field: ADDRESS_1 */
/********************/
`define ADDRESS_1_field_addr 21
// Defines for register "scan_in_addr_address_1_r0"
`define scan_in_addr_address_1_r0_LSbit 168
`define scan_in_addr_address_1_r0_MSbit 169
`define scan_in_addr_address_1_r0_Sel 169:168
`define scan_in_addr_address_1_r0_Width 2
`define scan_in_addr_address_1_r0_LSbit_Addr 21
`define scan_in_addr_address_1_r0_MSbit_Addr 21
`define scan_in_addr_address_1_r0_LSbit_Pos 0
`define scan_in_addr_address_1_r0_MSbit_Pos 1
// Defines for register "scan_in_addr_lb_sel_1_r0"
`define scan_in_addr_lb_sel_1_r0_LSbit 170
`define scan_in_addr_lb_sel_1_r0_MSbit 173
`define scan_in_addr_lb_sel_1_r0_Sel 173:170
`define scan_in_addr_lb_sel_1_r0_Width 4
`define scan_in_addr_lb_sel_1_r0_LSbit_Addr 21
`define scan_in_addr_lb_sel_1_r0_MSbit_Addr 21
`define scan_in_addr_lb_sel_1_r0_LSbit_Pos 2
`define scan_in_addr_lb_sel_1_r0_MSbit_Pos 5
// Defines for register "scan_in_addr_enable_1_r0"
`define scan_in_addr_enable_1_r0_LSbit 174
`define scan_in_addr_enable_1_r0_MSbit 174
`define scan_in_addr_enable_1_r0_Sel 174:174
`define scan_in_addr_enable_1_r0_Width 1
`define scan_in_addr_enable_1_r0_LSbit_Addr 21
`define scan_in_addr_enable_1_r0_MSbit_Addr 21
`define scan_in_addr_enable_1_r0_LSbit_Pos 6
`define scan_in_addr_enable_1_r0_MSbit_Pos 6
// Defines for register "scan_in_addr_address_1_r1"
`define scan_in_addr_address_1_r1_LSbit 175
`define scan_in_addr_address_1_r1_MSbit 176
`define scan_in_addr_address_1_r1_Sel 176:175
`define scan_in_addr_address_1_r1_Width 2
`define scan_in_addr_address_1_r1_LSbit_Addr 21
`define scan_in_addr_address_1_r1_MSbit_Addr 22
`define scan_in_addr_address_1_r1_LSbit_Pos 7
`define scan_in_addr_address_1_r1_MSbit_Pos 0
// Defines for register "scan_in_addr_lb_sel_1_r1"
`define scan_in_addr_lb_sel_1_r1_LSbit 177
`define scan_in_addr_lb_sel_1_r1_MSbit 180
`define scan_in_addr_lb_sel_1_r1_Sel 180:177
`define scan_in_addr_lb_sel_1_r1_Width 4
`define scan_in_addr_lb_sel_1_r1_LSbit_Addr 22
`define scan_in_addr_lb_sel_1_r1_MSbit_Addr 22
`define scan_in_addr_lb_sel_1_r1_LSbit_Pos 1
`define scan_in_addr_lb_sel_1_r1_MSbit_Pos 4
// Defines for register "scan_in_addr_enable_1_r1"
`define scan_in_addr_enable_1_r1_LSbit 181
`define scan_in_addr_enable_1_r1_MSbit 181
`define scan_in_addr_enable_1_r1_Sel 181:181
`define scan_in_addr_enable_1_r1_Width 1
`define scan_in_addr_enable_1_r1_LSbit_Addr 22
`define scan_in_addr_enable_1_r1_MSbit_Addr 22
`define scan_in_addr_enable_1_r1_LSbit_Pos 5
`define scan_in_addr_enable_1_r1_MSbit_Pos 5
// Defines for register "scan_in_addr_address_1_r2"
`define scan_in_addr_address_1_r2_LSbit 182
`define scan_in_addr_address_1_r2_MSbit 183
`define scan_in_addr_address_1_r2_Sel 183:182
`define scan_in_addr_address_1_r2_Width 2
`define scan_in_addr_address_1_r2_LSbit_Addr 22
`define scan_in_addr_address_1_r2_MSbit_Addr 22
`define scan_in_addr_address_1_r2_LSbit_Pos 6
`define scan_in_addr_address_1_r2_MSbit_Pos 7
// Defines for register "scan_in_addr_lb_sel_1_r2"
`define scan_in_addr_lb_sel_1_r2_LSbit 184
`define scan_in_addr_lb_sel_1_r2_MSbit 187
`define scan_in_addr_lb_sel_1_r2_Sel 187:184
`define scan_in_addr_lb_sel_1_r2_Width 4
`define scan_in_addr_lb_sel_1_r2_LSbit_Addr 23
`define scan_in_addr_lb_sel_1_r2_MSbit_Addr 23
`define scan_in_addr_lb_sel_1_r2_LSbit_Pos 0
`define scan_in_addr_lb_sel_1_r2_MSbit_Pos 3
// Defines for register "scan_in_addr_enable_1_r2"
`define scan_in_addr_enable_1_r2_LSbit 188
`define scan_in_addr_enable_1_r2_MSbit 188
`define scan_in_addr_enable_1_r2_Sel 188:188
`define scan_in_addr_enable_1_r2_Width 1
`define scan_in_addr_enable_1_r2_LSbit_Addr 23
`define scan_in_addr_enable_1_r2_MSbit_Addr 23
`define scan_in_addr_enable_1_r2_LSbit_Pos 4
`define scan_in_addr_enable_1_r2_MSbit_Pos 4
// Defines for register "scan_in_addr_address_1_r3"
`define scan_in_addr_address_1_r3_LSbit 189
`define scan_in_addr_address_1_r3_MSbit 190
`define scan_in_addr_address_1_r3_Sel 190:189
`define scan_in_addr_address_1_r3_Width 2
`define scan_in_addr_address_1_r3_LSbit_Addr 23
`define scan_in_addr_address_1_r3_MSbit_Addr 23
`define scan_in_addr_address_1_r3_LSbit_Pos 5
`define scan_in_addr_address_1_r3_MSbit_Pos 6
// Defines for register "scan_in_addr_lb_sel_1_r3"
`define scan_in_addr_lb_sel_1_r3_LSbit 191
`define scan_in_addr_lb_sel_1_r3_MSbit 194
`define scan_in_addr_lb_sel_1_r3_Sel 194:191
`define scan_in_addr_lb_sel_1_r3_Width 4
`define scan_in_addr_lb_sel_1_r3_LSbit_Addr 23
`define scan_in_addr_lb_sel_1_r3_MSbit_Addr 24
`define scan_in_addr_lb_sel_1_r3_LSbit_Pos 7
`define scan_in_addr_lb_sel_1_r3_MSbit_Pos 2
// Defines for register "scan_in_addr_enable_1_r3"
`define scan_in_addr_enable_1_r3_LSbit 195
`define scan_in_addr_enable_1_r3_MSbit 195
`define scan_in_addr_enable_1_r3_Sel 195:195
`define scan_in_addr_enable_1_r3_Width 1
`define scan_in_addr_enable_1_r3_LSbit_Addr 24
`define scan_in_addr_enable_1_r3_MSbit_Addr 24
`define scan_in_addr_enable_1_r3_LSbit_Pos 3
`define scan_in_addr_enable_1_r3_MSbit_Pos 3
// Defines for register "scan_in_addr_req_1"
`define scan_in_addr_req_1_LSbit 196
`define scan_in_addr_req_1_MSbit 196
`define scan_in_addr_req_1_Sel 196:196
`define scan_in_addr_req_1_Width 1
`define scan_in_addr_req_1_LSbit_Addr 24
`define scan_in_addr_req_1_MSbit_Addr 24
`define scan_in_addr_req_1_LSbit_Pos 4
`define scan_in_addr_req_1_MSbit_Pos 4
// Defines for register "scan_in_addr_cmd_1"
`define scan_in_addr_cmd_1_LSbit 197
`define scan_in_addr_cmd_1_MSbit 198
`define scan_in_addr_cmd_1_Sel 198:197
`define scan_in_addr_cmd_1_Width 2
`define scan_in_addr_cmd_1_LSbit_Addr 24
`define scan_in_addr_cmd_1_MSbit_Addr 24
`define scan_in_addr_cmd_1_LSbit_Pos 5
`define scan_in_addr_cmd_1_MSbit_Pos 6
// Defines for register "scan_in_addr_ack_1"
`define scan_in_addr_ack_1_LSbit 199
`define scan_in_addr_ack_1_MSbit 199
`define scan_in_addr_ack_1_Sel 199:199
`define scan_in_addr_ack_1_Width 1
`define scan_in_addr_ack_1_LSbit_Addr 24
`define scan_in_addr_ack_1_MSbit_Addr 24
`define scan_in_addr_ack_1_LSbit_Pos 7
`define scan_in_addr_ack_1_MSbit_Pos 7
// Field ADDRESS_1 length
`define ADDRESS_1_field_bit_length 32
`define ADDRESS_1_field_byte_length 4

/********************/
/* Field: ADDRESS_2 */
/********************/
`define ADDRESS_2_field_addr 25
// Defines for register "scan_in_addr_address_2_r0"
`define scan_in_addr_address_2_r0_LSbit 200
`define scan_in_addr_address_2_r0_MSbit 201
`define scan_in_addr_address_2_r0_Sel 201:200
`define scan_in_addr_address_2_r0_Width 2
`define scan_in_addr_address_2_r0_LSbit_Addr 25
`define scan_in_addr_address_2_r0_MSbit_Addr 25
`define scan_in_addr_address_2_r0_LSbit_Pos 0
`define scan_in_addr_address_2_r0_MSbit_Pos 1
// Defines for register "scan_in_addr_lb_sel_2_r0"
`define scan_in_addr_lb_sel_2_r0_LSbit 202
`define scan_in_addr_lb_sel_2_r0_MSbit 205
`define scan_in_addr_lb_sel_2_r0_Sel 205:202
`define scan_in_addr_lb_sel_2_r0_Width 4
`define scan_in_addr_lb_sel_2_r0_LSbit_Addr 25
`define scan_in_addr_lb_sel_2_r0_MSbit_Addr 25
`define scan_in_addr_lb_sel_2_r0_LSbit_Pos 2
`define scan_in_addr_lb_sel_2_r0_MSbit_Pos 5
// Defines for register "scan_in_addr_enable_2_r0"
`define scan_in_addr_enable_2_r0_LSbit 206
`define scan_in_addr_enable_2_r0_MSbit 206
`define scan_in_addr_enable_2_r0_Sel 206:206
`define scan_in_addr_enable_2_r0_Width 1
`define scan_in_addr_enable_2_r0_LSbit_Addr 25
`define scan_in_addr_enable_2_r0_MSbit_Addr 25
`define scan_in_addr_enable_2_r0_LSbit_Pos 6
`define scan_in_addr_enable_2_r0_MSbit_Pos 6
// Defines for register "scan_in_addr_address_2_r1"
`define scan_in_addr_address_2_r1_LSbit 207
`define scan_in_addr_address_2_r1_MSbit 208
`define scan_in_addr_address_2_r1_Sel 208:207
`define scan_in_addr_address_2_r1_Width 2
`define scan_in_addr_address_2_r1_LSbit_Addr 25
`define scan_in_addr_address_2_r1_MSbit_Addr 26
`define scan_in_addr_address_2_r1_LSbit_Pos 7
`define scan_in_addr_address_2_r1_MSbit_Pos 0
// Defines for register "scan_in_addr_lb_sel_2_r1"
`define scan_in_addr_lb_sel_2_r1_LSbit 209
`define scan_in_addr_lb_sel_2_r1_MSbit 212
`define scan_in_addr_lb_sel_2_r1_Sel 212:209
`define scan_in_addr_lb_sel_2_r1_Width 4
`define scan_in_addr_lb_sel_2_r1_LSbit_Addr 26
`define scan_in_addr_lb_sel_2_r1_MSbit_Addr 26
`define scan_in_addr_lb_sel_2_r1_LSbit_Pos 1
`define scan_in_addr_lb_sel_2_r1_MSbit_Pos 4
// Defines for register "scan_in_addr_enable_2_r1"
`define scan_in_addr_enable_2_r1_LSbit 213
`define scan_in_addr_enable_2_r1_MSbit 213
`define scan_in_addr_enable_2_r1_Sel 213:213
`define scan_in_addr_enable_2_r1_Width 1
`define scan_in_addr_enable_2_r1_LSbit_Addr 26
`define scan_in_addr_enable_2_r1_MSbit_Addr 26
`define scan_in_addr_enable_2_r1_LSbit_Pos 5
`define scan_in_addr_enable_2_r1_MSbit_Pos 5
// Defines for register "scan_in_addr_address_2_r2"
`define scan_in_addr_address_2_r2_LSbit 214
`define scan_in_addr_address_2_r2_MSbit 215
`define scan_in_addr_address_2_r2_Sel 215:214
`define scan_in_addr_address_2_r2_Width 2
`define scan_in_addr_address_2_r2_LSbit_Addr 26
`define scan_in_addr_address_2_r2_MSbit_Addr 26
`define scan_in_addr_address_2_r2_LSbit_Pos 6
`define scan_in_addr_address_2_r2_MSbit_Pos 7
// Defines for register "scan_in_addr_lb_sel_2_r2"
`define scan_in_addr_lb_sel_2_r2_LSbit 216
`define scan_in_addr_lb_sel_2_r2_MSbit 219
`define scan_in_addr_lb_sel_2_r2_Sel 219:216
`define scan_in_addr_lb_sel_2_r2_Width 4
`define scan_in_addr_lb_sel_2_r2_LSbit_Addr 27
`define scan_in_addr_lb_sel_2_r2_MSbit_Addr 27
`define scan_in_addr_lb_sel_2_r2_LSbit_Pos 0
`define scan_in_addr_lb_sel_2_r2_MSbit_Pos 3
// Defines for register "scan_in_addr_enable_2_r2"
`define scan_in_addr_enable_2_r2_LSbit 220
`define scan_in_addr_enable_2_r2_MSbit 220
`define scan_in_addr_enable_2_r2_Sel 220:220
`define scan_in_addr_enable_2_r2_Width 1
`define scan_in_addr_enable_2_r2_LSbit_Addr 27
`define scan_in_addr_enable_2_r2_MSbit_Addr 27
`define scan_in_addr_enable_2_r2_LSbit_Pos 4
`define scan_in_addr_enable_2_r2_MSbit_Pos 4
// Defines for register "scan_in_addr_address_2_r3"
`define scan_in_addr_address_2_r3_LSbit 221
`define scan_in_addr_address_2_r3_MSbit 222
`define scan_in_addr_address_2_r3_Sel 222:221
`define scan_in_addr_address_2_r3_Width 2
`define scan_in_addr_address_2_r3_LSbit_Addr 27
`define scan_in_addr_address_2_r3_MSbit_Addr 27
`define scan_in_addr_address_2_r3_LSbit_Pos 5
`define scan_in_addr_address_2_r3_MSbit_Pos 6
// Defines for register "scan_in_addr_lb_sel_2_r3"
`define scan_in_addr_lb_sel_2_r3_LSbit 223
`define scan_in_addr_lb_sel_2_r3_MSbit 226
`define scan_in_addr_lb_sel_2_r3_Sel 226:223
`define scan_in_addr_lb_sel_2_r3_Width 4
`define scan_in_addr_lb_sel_2_r3_LSbit_Addr 27
`define scan_in_addr_lb_sel_2_r3_MSbit_Addr 28
`define scan_in_addr_lb_sel_2_r3_LSbit_Pos 7
`define scan_in_addr_lb_sel_2_r3_MSbit_Pos 2
// Defines for register "scan_in_addr_enable_2_r3"
`define scan_in_addr_enable_2_r3_LSbit 227
`define scan_in_addr_enable_2_r3_MSbit 227
`define scan_in_addr_enable_2_r3_Sel 227:227
`define scan_in_addr_enable_2_r3_Width 1
`define scan_in_addr_enable_2_r3_LSbit_Addr 28
`define scan_in_addr_enable_2_r3_MSbit_Addr 28
`define scan_in_addr_enable_2_r3_LSbit_Pos 3
`define scan_in_addr_enable_2_r3_MSbit_Pos 3
// Defines for register "scan_in_addr_req_2"
`define scan_in_addr_req_2_LSbit 228
`define scan_in_addr_req_2_MSbit 228
`define scan_in_addr_req_2_Sel 228:228
`define scan_in_addr_req_2_Width 1
`define scan_in_addr_req_2_LSbit_Addr 28
`define scan_in_addr_req_2_MSbit_Addr 28
`define scan_in_addr_req_2_LSbit_Pos 4
`define scan_in_addr_req_2_MSbit_Pos 4
// Defines for register "scan_in_addr_cmd_2"
`define scan_in_addr_cmd_2_LSbit 229
`define scan_in_addr_cmd_2_MSbit 230
`define scan_in_addr_cmd_2_Sel 230:229
`define scan_in_addr_cmd_2_Width 2
`define scan_in_addr_cmd_2_LSbit_Addr 28
`define scan_in_addr_cmd_2_MSbit_Addr 28
`define scan_in_addr_cmd_2_LSbit_Pos 5
`define scan_in_addr_cmd_2_MSbit_Pos 6
// Defines for register "scan_in_addr_ack_2"
`define scan_in_addr_ack_2_LSbit 231
`define scan_in_addr_ack_2_MSbit 231
`define scan_in_addr_ack_2_Sel 231:231
`define scan_in_addr_ack_2_Width 1
`define scan_in_addr_ack_2_LSbit_Addr 28
`define scan_in_addr_ack_2_MSbit_Addr 28
`define scan_in_addr_ack_2_LSbit_Pos 7
`define scan_in_addr_ack_2_MSbit_Pos 7
// Field ADDRESS_2 length
`define ADDRESS_2_field_bit_length 32
`define ADDRESS_2_field_byte_length 4

/********************/
/* Field: ADDRESS_3 */
/********************/
`define ADDRESS_3_field_addr 29
// Defines for register "scan_in_addr_address_3_r0"
`define scan_in_addr_address_3_r0_LSbit 232
`define scan_in_addr_address_3_r0_MSbit 233
`define scan_in_addr_address_3_r0_Sel 233:232
`define scan_in_addr_address_3_r0_Width 2
`define scan_in_addr_address_3_r0_LSbit_Addr 29
`define scan_in_addr_address_3_r0_MSbit_Addr 29
`define scan_in_addr_address_3_r0_LSbit_Pos 0
`define scan_in_addr_address_3_r0_MSbit_Pos 1
// Defines for register "scan_in_addr_lb_sel_3_r0"
`define scan_in_addr_lb_sel_3_r0_LSbit 234
`define scan_in_addr_lb_sel_3_r0_MSbit 237
`define scan_in_addr_lb_sel_3_r0_Sel 237:234
`define scan_in_addr_lb_sel_3_r0_Width 4
`define scan_in_addr_lb_sel_3_r0_LSbit_Addr 29
`define scan_in_addr_lb_sel_3_r0_MSbit_Addr 29
`define scan_in_addr_lb_sel_3_r0_LSbit_Pos 2
`define scan_in_addr_lb_sel_3_r0_MSbit_Pos 5
// Defines for register "scan_in_addr_enable_3_r0"
`define scan_in_addr_enable_3_r0_LSbit 238
`define scan_in_addr_enable_3_r0_MSbit 238
`define scan_in_addr_enable_3_r0_Sel 238:238
`define scan_in_addr_enable_3_r0_Width 1
`define scan_in_addr_enable_3_r0_LSbit_Addr 29
`define scan_in_addr_enable_3_r0_MSbit_Addr 29
`define scan_in_addr_enable_3_r0_LSbit_Pos 6
`define scan_in_addr_enable_3_r0_MSbit_Pos 6
// Defines for register "scan_in_addr_address_3_r1"
`define scan_in_addr_address_3_r1_LSbit 239
`define scan_in_addr_address_3_r1_MSbit 240
`define scan_in_addr_address_3_r1_Sel 240:239
`define scan_in_addr_address_3_r1_Width 2
`define scan_in_addr_address_3_r1_LSbit_Addr 29
`define scan_in_addr_address_3_r1_MSbit_Addr 30
`define scan_in_addr_address_3_r1_LSbit_Pos 7
`define scan_in_addr_address_3_r1_MSbit_Pos 0
// Defines for register "scan_in_addr_lb_sel_3_r1"
`define scan_in_addr_lb_sel_3_r1_LSbit 241
`define scan_in_addr_lb_sel_3_r1_MSbit 244
`define scan_in_addr_lb_sel_3_r1_Sel 244:241
`define scan_in_addr_lb_sel_3_r1_Width 4
`define scan_in_addr_lb_sel_3_r1_LSbit_Addr 30
`define scan_in_addr_lb_sel_3_r1_MSbit_Addr 30
`define scan_in_addr_lb_sel_3_r1_LSbit_Pos 1
`define scan_in_addr_lb_sel_3_r1_MSbit_Pos 4
// Defines for register "scan_in_addr_enable_3_r1"
`define scan_in_addr_enable_3_r1_LSbit 245
`define scan_in_addr_enable_3_r1_MSbit 245
`define scan_in_addr_enable_3_r1_Sel 245:245
`define scan_in_addr_enable_3_r1_Width 1
`define scan_in_addr_enable_3_r1_LSbit_Addr 30
`define scan_in_addr_enable_3_r1_MSbit_Addr 30
`define scan_in_addr_enable_3_r1_LSbit_Pos 5
`define scan_in_addr_enable_3_r1_MSbit_Pos 5
// Defines for register "scan_in_addr_address_3_r2"
`define scan_in_addr_address_3_r2_LSbit 246
`define scan_in_addr_address_3_r2_MSbit 247
`define scan_in_addr_address_3_r2_Sel 247:246
`define scan_in_addr_address_3_r2_Width 2
`define scan_in_addr_address_3_r2_LSbit_Addr 30
`define scan_in_addr_address_3_r2_MSbit_Addr 30
`define scan_in_addr_address_3_r2_LSbit_Pos 6
`define scan_in_addr_address_3_r2_MSbit_Pos 7
// Defines for register "scan_in_addr_lb_sel_3_r2"
`define scan_in_addr_lb_sel_3_r2_LSbit 248
`define scan_in_addr_lb_sel_3_r2_MSbit 251
`define scan_in_addr_lb_sel_3_r2_Sel 251:248
`define scan_in_addr_lb_sel_3_r2_Width 4
`define scan_in_addr_lb_sel_3_r2_LSbit_Addr 31
`define scan_in_addr_lb_sel_3_r2_MSbit_Addr 31
`define scan_in_addr_lb_sel_3_r2_LSbit_Pos 0
`define scan_in_addr_lb_sel_3_r2_MSbit_Pos 3
// Defines for register "scan_in_addr_enable_3_r2"
`define scan_in_addr_enable_3_r2_LSbit 252
`define scan_in_addr_enable_3_r2_MSbit 252
`define scan_in_addr_enable_3_r2_Sel 252:252
`define scan_in_addr_enable_3_r2_Width 1
`define scan_in_addr_enable_3_r2_LSbit_Addr 31
`define scan_in_addr_enable_3_r2_MSbit_Addr 31
`define scan_in_addr_enable_3_r2_LSbit_Pos 4
`define scan_in_addr_enable_3_r2_MSbit_Pos 4
// Defines for register "scan_in_addr_address_3_r3"
`define scan_in_addr_address_3_r3_LSbit 253
`define scan_in_addr_address_3_r3_MSbit 254
`define scan_in_addr_address_3_r3_Sel 254:253
`define scan_in_addr_address_3_r3_Width 2
`define scan_in_addr_address_3_r3_LSbit_Addr 31
`define scan_in_addr_address_3_r3_MSbit_Addr 31
`define scan_in_addr_address_3_r3_LSbit_Pos 5
`define scan_in_addr_address_3_r3_MSbit_Pos 6
// Defines for register "scan_in_addr_lb_sel_3_r3"
`define scan_in_addr_lb_sel_3_r3_LSbit 255
`define scan_in_addr_lb_sel_3_r3_MSbit 258
`define scan_in_addr_lb_sel_3_r3_Sel 258:255
`define scan_in_addr_lb_sel_3_r3_Width 4
`define scan_in_addr_lb_sel_3_r3_LSbit_Addr 31
`define scan_in_addr_lb_sel_3_r3_MSbit_Addr 32
`define scan_in_addr_lb_sel_3_r3_LSbit_Pos 7
`define scan_in_addr_lb_sel_3_r3_MSbit_Pos 2
// Defines for register "scan_in_addr_enable_3_r3"
`define scan_in_addr_enable_3_r3_LSbit 259
`define scan_in_addr_enable_3_r3_MSbit 259
`define scan_in_addr_enable_3_r3_Sel 259:259
`define scan_in_addr_enable_3_r3_Width 1
`define scan_in_addr_enable_3_r3_LSbit_Addr 32
`define scan_in_addr_enable_3_r3_MSbit_Addr 32
`define scan_in_addr_enable_3_r3_LSbit_Pos 3
`define scan_in_addr_enable_3_r3_MSbit_Pos 3
// Defines for register "scan_in_addr_req_3"
`define scan_in_addr_req_3_LSbit 260
`define scan_in_addr_req_3_MSbit 260
`define scan_in_addr_req_3_Sel 260:260
`define scan_in_addr_req_3_Width 1
`define scan_in_addr_req_3_LSbit_Addr 32
`define scan_in_addr_req_3_MSbit_Addr 32
`define scan_in_addr_req_3_LSbit_Pos 4
`define scan_in_addr_req_3_MSbit_Pos 4
// Defines for register "scan_in_addr_cmd_3"
`define scan_in_addr_cmd_3_LSbit 261
`define scan_in_addr_cmd_3_MSbit 262
`define scan_in_addr_cmd_3_Sel 262:261
`define scan_in_addr_cmd_3_Width 2
`define scan_in_addr_cmd_3_LSbit_Addr 32
`define scan_in_addr_cmd_3_MSbit_Addr 32
`define scan_in_addr_cmd_3_LSbit_Pos 5
`define scan_in_addr_cmd_3_MSbit_Pos 6
// Defines for register "scan_in_addr_ack_3"
`define scan_in_addr_ack_3_LSbit 263
`define scan_in_addr_ack_3_MSbit 263
`define scan_in_addr_ack_3_Sel 263:263
`define scan_in_addr_ack_3_Width 1
`define scan_in_addr_ack_3_LSbit_Addr 32
`define scan_in_addr_ack_3_MSbit_Addr 32
`define scan_in_addr_ack_3_LSbit_Pos 7
`define scan_in_addr_ack_3_MSbit_Pos 7
// Field ADDRESS_3 length
`define ADDRESS_3_field_bit_length 32
`define ADDRESS_3_field_byte_length 4

/************************/
/* Field: INSTRUCTION_0 */
/************************/
`define INSTRUCTION_0_field_addr 33
// Defines for register "scan_in_inst_0_data_0"
`define scan_in_inst_0_data_0_LSbit 264
`define scan_in_inst_0_data_0_MSbit 270
`define scan_in_inst_0_data_0_Sel 270:264
`define scan_in_inst_0_data_0_Width 7
`define scan_in_inst_0_data_0_LSbit_Addr 33
`define scan_in_inst_0_data_0_MSbit_Addr 33
`define scan_in_inst_0_data_0_LSbit_Pos 0
`define scan_in_inst_0_data_0_MSbit_Pos 6
// Defines for register "scan_in_inst_1_data_0"
`define scan_in_inst_1_data_0_LSbit 271
`define scan_in_inst_1_data_0_MSbit 277
`define scan_in_inst_1_data_0_Sel 277:271
`define scan_in_inst_1_data_0_Width 7
`define scan_in_inst_1_data_0_LSbit_Addr 33
`define scan_in_inst_1_data_0_MSbit_Addr 34
`define scan_in_inst_1_data_0_LSbit_Pos 7
`define scan_in_inst_1_data_0_MSbit_Pos 5
// Defines for register "scan_in_inst_2_data_0"
`define scan_in_inst_2_data_0_LSbit 278
`define scan_in_inst_2_data_0_MSbit 284
`define scan_in_inst_2_data_0_Sel 284:278
`define scan_in_inst_2_data_0_Width 7
`define scan_in_inst_2_data_0_LSbit_Addr 34
`define scan_in_inst_2_data_0_MSbit_Addr 35
`define scan_in_inst_2_data_0_LSbit_Pos 6
`define scan_in_inst_2_data_0_MSbit_Pos 4
// Defines for register "scan_in_inst_3_data_0"
`define scan_in_inst_3_data_0_LSbit 285
`define scan_in_inst_3_data_0_MSbit 291
`define scan_in_inst_3_data_0_Sel 291:285
`define scan_in_inst_3_data_0_Width 7
`define scan_in_inst_3_data_0_LSbit_Addr 35
`define scan_in_inst_3_data_0_MSbit_Addr 36
`define scan_in_inst_3_data_0_LSbit_Pos 5
`define scan_in_inst_3_data_0_MSbit_Pos 3
// Defines for register "scan_in_inst_4_data_0"
`define scan_in_inst_4_data_0_LSbit 292
`define scan_in_inst_4_data_0_MSbit 298
`define scan_in_inst_4_data_0_Sel 298:292
`define scan_in_inst_4_data_0_Width 7
`define scan_in_inst_4_data_0_LSbit_Addr 36
`define scan_in_inst_4_data_0_MSbit_Addr 37
`define scan_in_inst_4_data_0_LSbit_Pos 4
`define scan_in_inst_4_data_0_MSbit_Pos 2
// Defines for register "scan_in_inst_5_data_0"
`define scan_in_inst_5_data_0_LSbit 299
`define scan_in_inst_5_data_0_MSbit 305
`define scan_in_inst_5_data_0_Sel 305:299
`define scan_in_inst_5_data_0_Width 7
`define scan_in_inst_5_data_0_LSbit_Addr 37
`define scan_in_inst_5_data_0_MSbit_Addr 38
`define scan_in_inst_5_data_0_LSbit_Pos 3
`define scan_in_inst_5_data_0_MSbit_Pos 1
// Defines for register "scan_in_inst_6_data_0"
`define scan_in_inst_6_data_0_LSbit 306
`define scan_in_inst_6_data_0_MSbit 312
`define scan_in_inst_6_data_0_Sel 312:306
`define scan_in_inst_6_data_0_Width 7
`define scan_in_inst_6_data_0_LSbit_Addr 38
`define scan_in_inst_6_data_0_MSbit_Addr 39
`define scan_in_inst_6_data_0_LSbit_Pos 2
`define scan_in_inst_6_data_0_MSbit_Pos 0
// Defines for register "scan_in_inst_7_data_0"
`define scan_in_inst_7_data_0_LSbit 313
`define scan_in_inst_7_data_0_MSbit 319
`define scan_in_inst_7_data_0_Sel 319:313
`define scan_in_inst_7_data_0_Width 7
`define scan_in_inst_7_data_0_LSbit_Addr 39
`define scan_in_inst_7_data_0_MSbit_Addr 39
`define scan_in_inst_7_data_0_LSbit_Pos 1
`define scan_in_inst_7_data_0_MSbit_Pos 7
// Defines for register "scan_in_inst_8_data_0"
`define scan_in_inst_8_data_0_LSbit 320
`define scan_in_inst_8_data_0_MSbit 326
`define scan_in_inst_8_data_0_Sel 326:320
`define scan_in_inst_8_data_0_Width 7
`define scan_in_inst_8_data_0_LSbit_Addr 40
`define scan_in_inst_8_data_0_MSbit_Addr 40
`define scan_in_inst_8_data_0_LSbit_Pos 0
`define scan_in_inst_8_data_0_MSbit_Pos 6
// Defines for register "scan_in_inst_9_data_0"
`define scan_in_inst_9_data_0_LSbit 327
`define scan_in_inst_9_data_0_MSbit 333
`define scan_in_inst_9_data_0_Sel 333:327
`define scan_in_inst_9_data_0_Width 7
`define scan_in_inst_9_data_0_LSbit_Addr 40
`define scan_in_inst_9_data_0_MSbit_Addr 41
`define scan_in_inst_9_data_0_LSbit_Pos 7
`define scan_in_inst_9_data_0_MSbit_Pos 5
// Defines for register "scan_in_inst_10_data_0"
`define scan_in_inst_10_data_0_LSbit 334
`define scan_in_inst_10_data_0_MSbit 340
`define scan_in_inst_10_data_0_Sel 340:334
`define scan_in_inst_10_data_0_Width 7
`define scan_in_inst_10_data_0_LSbit_Addr 41
`define scan_in_inst_10_data_0_MSbit_Addr 42
`define scan_in_inst_10_data_0_LSbit_Pos 6
`define scan_in_inst_10_data_0_MSbit_Pos 4
// Defines for register "scan_in_inst_11_data_0"
`define scan_in_inst_11_data_0_LSbit 341
`define scan_in_inst_11_data_0_MSbit 347
`define scan_in_inst_11_data_0_Sel 347:341
`define scan_in_inst_11_data_0_Width 7
`define scan_in_inst_11_data_0_LSbit_Addr 42
`define scan_in_inst_11_data_0_MSbit_Addr 43
`define scan_in_inst_11_data_0_LSbit_Pos 5
`define scan_in_inst_11_data_0_MSbit_Pos 3
// Defines for register "scan_in_inst_12_data_0"
`define scan_in_inst_12_data_0_LSbit 348
`define scan_in_inst_12_data_0_MSbit 354
`define scan_in_inst_12_data_0_Sel 354:348
`define scan_in_inst_12_data_0_Width 7
`define scan_in_inst_12_data_0_LSbit_Addr 43
`define scan_in_inst_12_data_0_MSbit_Addr 44
`define scan_in_inst_12_data_0_LSbit_Pos 4
`define scan_in_inst_12_data_0_MSbit_Pos 2
// Defines for register "scan_in_inst_13_data_0"
`define scan_in_inst_13_data_0_LSbit 355
`define scan_in_inst_13_data_0_MSbit 361
`define scan_in_inst_13_data_0_Sel 361:355
`define scan_in_inst_13_data_0_Width 7
`define scan_in_inst_13_data_0_LSbit_Addr 44
`define scan_in_inst_13_data_0_MSbit_Addr 45
`define scan_in_inst_13_data_0_LSbit_Pos 3
`define scan_in_inst_13_data_0_MSbit_Pos 1
// Defines for register "scan_in_inst_14_data_0"
`define scan_in_inst_14_data_0_LSbit 362
`define scan_in_inst_14_data_0_MSbit 368
`define scan_in_inst_14_data_0_Sel 368:362
`define scan_in_inst_14_data_0_Width 7
`define scan_in_inst_14_data_0_LSbit_Addr 45
`define scan_in_inst_14_data_0_MSbit_Addr 46
`define scan_in_inst_14_data_0_LSbit_Pos 2
`define scan_in_inst_14_data_0_MSbit_Pos 0
// Defines for register "scan_in_inst_15_data_0"
`define scan_in_inst_15_data_0_LSbit 369
`define scan_in_inst_15_data_0_MSbit 375
`define scan_in_inst_15_data_0_Sel 375:369
`define scan_in_inst_15_data_0_Width 7
`define scan_in_inst_15_data_0_LSbit_Addr 46
`define scan_in_inst_15_data_0_MSbit_Addr 46
`define scan_in_inst_15_data_0_LSbit_Pos 1
`define scan_in_inst_15_data_0_MSbit_Pos 7
// Defines for register "scan_in_inst_16_data_0"
`define scan_in_inst_16_data_0_LSbit 376
`define scan_in_inst_16_data_0_MSbit 382
`define scan_in_inst_16_data_0_Sel 382:376
`define scan_in_inst_16_data_0_Width 7
`define scan_in_inst_16_data_0_LSbit_Addr 47
`define scan_in_inst_16_data_0_MSbit_Addr 47
`define scan_in_inst_16_data_0_LSbit_Pos 0
`define scan_in_inst_16_data_0_MSbit_Pos 6
// Defines for register "scan_in_inst_17_data_0"
`define scan_in_inst_17_data_0_LSbit 383
`define scan_in_inst_17_data_0_MSbit 389
`define scan_in_inst_17_data_0_Sel 389:383
`define scan_in_inst_17_data_0_Width 7
`define scan_in_inst_17_data_0_LSbit_Addr 47
`define scan_in_inst_17_data_0_MSbit_Addr 48
`define scan_in_inst_17_data_0_LSbit_Pos 7
`define scan_in_inst_17_data_0_MSbit_Pos 5
// Defines for register "scan_in_inst_18_data_0"
`define scan_in_inst_18_data_0_LSbit 390
`define scan_in_inst_18_data_0_MSbit 396
`define scan_in_inst_18_data_0_Sel 396:390
`define scan_in_inst_18_data_0_Width 7
`define scan_in_inst_18_data_0_LSbit_Addr 48
`define scan_in_inst_18_data_0_MSbit_Addr 49
`define scan_in_inst_18_data_0_LSbit_Pos 6
`define scan_in_inst_18_data_0_MSbit_Pos 4
// Defines for register "scan_in_inst_19_data_0"
`define scan_in_inst_19_data_0_LSbit 397
`define scan_in_inst_19_data_0_MSbit 403
`define scan_in_inst_19_data_0_Sel 403:397
`define scan_in_inst_19_data_0_Width 7
`define scan_in_inst_19_data_0_LSbit_Addr 49
`define scan_in_inst_19_data_0_MSbit_Addr 50
`define scan_in_inst_19_data_0_LSbit_Pos 5
`define scan_in_inst_19_data_0_MSbit_Pos 3
// Defines for register "scan_in_inst_20_data_0"
`define scan_in_inst_20_data_0_LSbit 404
`define scan_in_inst_20_data_0_MSbit 410
`define scan_in_inst_20_data_0_Sel 410:404
`define scan_in_inst_20_data_0_Width 7
`define scan_in_inst_20_data_0_LSbit_Addr 50
`define scan_in_inst_20_data_0_MSbit_Addr 51
`define scan_in_inst_20_data_0_LSbit_Pos 4
`define scan_in_inst_20_data_0_MSbit_Pos 2
// Defines for register "scan_in_inst_21_data_0"
`define scan_in_inst_21_data_0_LSbit 411
`define scan_in_inst_21_data_0_MSbit 417
`define scan_in_inst_21_data_0_Sel 417:411
`define scan_in_inst_21_data_0_Width 7
`define scan_in_inst_21_data_0_LSbit_Addr 51
`define scan_in_inst_21_data_0_MSbit_Addr 52
`define scan_in_inst_21_data_0_LSbit_Pos 3
`define scan_in_inst_21_data_0_MSbit_Pos 1
// Defines for register "scan_in_inst_22_data_0"
`define scan_in_inst_22_data_0_LSbit 418
`define scan_in_inst_22_data_0_MSbit 424
`define scan_in_inst_22_data_0_Sel 424:418
`define scan_in_inst_22_data_0_Width 7
`define scan_in_inst_22_data_0_LSbit_Addr 52
`define scan_in_inst_22_data_0_MSbit_Addr 53
`define scan_in_inst_22_data_0_LSbit_Pos 2
`define scan_in_inst_22_data_0_MSbit_Pos 0
// Defines for register "scan_in_inst_23_data_0"
`define scan_in_inst_23_data_0_LSbit 425
`define scan_in_inst_23_data_0_MSbit 431
`define scan_in_inst_23_data_0_Sel 431:425
`define scan_in_inst_23_data_0_Width 7
`define scan_in_inst_23_data_0_LSbit_Addr 53
`define scan_in_inst_23_data_0_MSbit_Addr 53
`define scan_in_inst_23_data_0_LSbit_Pos 1
`define scan_in_inst_23_data_0_MSbit_Pos 7
// Defines for register "scan_in_inst_24_data_0"
`define scan_in_inst_24_data_0_LSbit 432
`define scan_in_inst_24_data_0_MSbit 438
`define scan_in_inst_24_data_0_Sel 438:432
`define scan_in_inst_24_data_0_Width 7
`define scan_in_inst_24_data_0_LSbit_Addr 54
`define scan_in_inst_24_data_0_MSbit_Addr 54
`define scan_in_inst_24_data_0_LSbit_Pos 0
`define scan_in_inst_24_data_0_MSbit_Pos 6
// Defines for register "scan_in_inst_25_data_0"
`define scan_in_inst_25_data_0_LSbit 439
`define scan_in_inst_25_data_0_MSbit 445
`define scan_in_inst_25_data_0_Sel 445:439
`define scan_in_inst_25_data_0_Width 7
`define scan_in_inst_25_data_0_LSbit_Addr 54
`define scan_in_inst_25_data_0_MSbit_Addr 55
`define scan_in_inst_25_data_0_LSbit_Pos 7
`define scan_in_inst_25_data_0_MSbit_Pos 5
// Defines for register "scan_in_inst_26_data_0"
`define scan_in_inst_26_data_0_LSbit 446
`define scan_in_inst_26_data_0_MSbit 452
`define scan_in_inst_26_data_0_Sel 452:446
`define scan_in_inst_26_data_0_Width 7
`define scan_in_inst_26_data_0_LSbit_Addr 55
`define scan_in_inst_26_data_0_MSbit_Addr 56
`define scan_in_inst_26_data_0_LSbit_Pos 6
`define scan_in_inst_26_data_0_MSbit_Pos 4
// Defines for register "scan_in_inst_27_data_0"
`define scan_in_inst_27_data_0_LSbit 453
`define scan_in_inst_27_data_0_MSbit 459
`define scan_in_inst_27_data_0_Sel 459:453
`define scan_in_inst_27_data_0_Width 7
`define scan_in_inst_27_data_0_LSbit_Addr 56
`define scan_in_inst_27_data_0_MSbit_Addr 57
`define scan_in_inst_27_data_0_LSbit_Pos 5
`define scan_in_inst_27_data_0_MSbit_Pos 3
// Defines for register "scan_in_inst_28_data_0"
`define scan_in_inst_28_data_0_LSbit 460
`define scan_in_inst_28_data_0_MSbit 466
`define scan_in_inst_28_data_0_Sel 466:460
`define scan_in_inst_28_data_0_Width 7
`define scan_in_inst_28_data_0_LSbit_Addr 57
`define scan_in_inst_28_data_0_MSbit_Addr 58
`define scan_in_inst_28_data_0_LSbit_Pos 4
`define scan_in_inst_28_data_0_MSbit_Pos 2
// Defines for register "scan_in_inst_29_data_0"
`define scan_in_inst_29_data_0_LSbit 467
`define scan_in_inst_29_data_0_MSbit 473
`define scan_in_inst_29_data_0_Sel 473:467
`define scan_in_inst_29_data_0_Width 7
`define scan_in_inst_29_data_0_LSbit_Addr 58
`define scan_in_inst_29_data_0_MSbit_Addr 59
`define scan_in_inst_29_data_0_LSbit_Pos 3
`define scan_in_inst_29_data_0_MSbit_Pos 1
// Defines for register "scan_in_inst_30_data_0"
`define scan_in_inst_30_data_0_LSbit 474
`define scan_in_inst_30_data_0_MSbit 480
`define scan_in_inst_30_data_0_Sel 480:474
`define scan_in_inst_30_data_0_Width 7
`define scan_in_inst_30_data_0_LSbit_Addr 59
`define scan_in_inst_30_data_0_MSbit_Addr 60
`define scan_in_inst_30_data_0_LSbit_Pos 2
`define scan_in_inst_30_data_0_MSbit_Pos 0
// Defines for register "scan_in_inst_31_data_0"
`define scan_in_inst_31_data_0_LSbit 481
`define scan_in_inst_31_data_0_MSbit 487
`define scan_in_inst_31_data_0_Sel 487:481
`define scan_in_inst_31_data_0_Width 7
`define scan_in_inst_31_data_0_LSbit_Addr 60
`define scan_in_inst_31_data_0_MSbit_Addr 60
`define scan_in_inst_31_data_0_LSbit_Pos 1
`define scan_in_inst_31_data_0_MSbit_Pos 7
// Defines for register "scan_in_inst_req_0"
`define scan_in_inst_req_0_LSbit 488
`define scan_in_inst_req_0_MSbit 488
`define scan_in_inst_req_0_Sel 488:488
`define scan_in_inst_req_0_Width 1
`define scan_in_inst_req_0_LSbit_Addr 61
`define scan_in_inst_req_0_MSbit_Addr 61
`define scan_in_inst_req_0_LSbit_Pos 0
`define scan_in_inst_req_0_MSbit_Pos 0
// Defines for register "scan_in_inst_cmd_0"
`define scan_in_inst_cmd_0_LSbit 489
`define scan_in_inst_cmd_0_MSbit 490
`define scan_in_inst_cmd_0_Sel 490:489
`define scan_in_inst_cmd_0_Width 2
`define scan_in_inst_cmd_0_LSbit_Addr 61
`define scan_in_inst_cmd_0_MSbit_Addr 61
`define scan_in_inst_cmd_0_LSbit_Pos 1
`define scan_in_inst_cmd_0_MSbit_Pos 2
// Defines for register "scan_in_inst_ack_0"
`define scan_in_inst_ack_0_LSbit 491
`define scan_in_inst_ack_0_MSbit 491
`define scan_in_inst_ack_0_Sel 491:491
`define scan_in_inst_ack_0_Width 1
`define scan_in_inst_ack_0_LSbit_Addr 61
`define scan_in_inst_ack_0_MSbit_Addr 61
`define scan_in_inst_ack_0_LSbit_Pos 3
`define scan_in_inst_ack_0_MSbit_Pos 3
// Field INSTRUCTION_0 length
`define INSTRUCTION_0_field_bit_length 228
`define INSTRUCTION_0_field_byte_length 29

/************************/
/* Field: INSTRUCTION_1 */
/************************/
`define INSTRUCTION_1_field_addr 62
// Defines for register "scan_in_inst_0_data_1"
`define scan_in_inst_0_data_1_LSbit 496
`define scan_in_inst_0_data_1_MSbit 502
`define scan_in_inst_0_data_1_Sel 502:496
`define scan_in_inst_0_data_1_Width 7
`define scan_in_inst_0_data_1_LSbit_Addr 62
`define scan_in_inst_0_data_1_MSbit_Addr 62
`define scan_in_inst_0_data_1_LSbit_Pos 0
`define scan_in_inst_0_data_1_MSbit_Pos 6
// Defines for register "scan_in_inst_1_data_1"
`define scan_in_inst_1_data_1_LSbit 503
`define scan_in_inst_1_data_1_MSbit 509
`define scan_in_inst_1_data_1_Sel 509:503
`define scan_in_inst_1_data_1_Width 7
`define scan_in_inst_1_data_1_LSbit_Addr 62
`define scan_in_inst_1_data_1_MSbit_Addr 63
`define scan_in_inst_1_data_1_LSbit_Pos 7
`define scan_in_inst_1_data_1_MSbit_Pos 5
// Defines for register "scan_in_inst_2_data_1"
`define scan_in_inst_2_data_1_LSbit 510
`define scan_in_inst_2_data_1_MSbit 516
`define scan_in_inst_2_data_1_Sel 516:510
`define scan_in_inst_2_data_1_Width 7
`define scan_in_inst_2_data_1_LSbit_Addr 63
`define scan_in_inst_2_data_1_MSbit_Addr 64
`define scan_in_inst_2_data_1_LSbit_Pos 6
`define scan_in_inst_2_data_1_MSbit_Pos 4
// Defines for register "scan_in_inst_3_data_1"
`define scan_in_inst_3_data_1_LSbit 517
`define scan_in_inst_3_data_1_MSbit 523
`define scan_in_inst_3_data_1_Sel 523:517
`define scan_in_inst_3_data_1_Width 7
`define scan_in_inst_3_data_1_LSbit_Addr 64
`define scan_in_inst_3_data_1_MSbit_Addr 65
`define scan_in_inst_3_data_1_LSbit_Pos 5
`define scan_in_inst_3_data_1_MSbit_Pos 3
// Defines for register "scan_in_inst_4_data_1"
`define scan_in_inst_4_data_1_LSbit 524
`define scan_in_inst_4_data_1_MSbit 530
`define scan_in_inst_4_data_1_Sel 530:524
`define scan_in_inst_4_data_1_Width 7
`define scan_in_inst_4_data_1_LSbit_Addr 65
`define scan_in_inst_4_data_1_MSbit_Addr 66
`define scan_in_inst_4_data_1_LSbit_Pos 4
`define scan_in_inst_4_data_1_MSbit_Pos 2
// Defines for register "scan_in_inst_5_data_1"
`define scan_in_inst_5_data_1_LSbit 531
`define scan_in_inst_5_data_1_MSbit 537
`define scan_in_inst_5_data_1_Sel 537:531
`define scan_in_inst_5_data_1_Width 7
`define scan_in_inst_5_data_1_LSbit_Addr 66
`define scan_in_inst_5_data_1_MSbit_Addr 67
`define scan_in_inst_5_data_1_LSbit_Pos 3
`define scan_in_inst_5_data_1_MSbit_Pos 1
// Defines for register "scan_in_inst_6_data_1"
`define scan_in_inst_6_data_1_LSbit 538
`define scan_in_inst_6_data_1_MSbit 544
`define scan_in_inst_6_data_1_Sel 544:538
`define scan_in_inst_6_data_1_Width 7
`define scan_in_inst_6_data_1_LSbit_Addr 67
`define scan_in_inst_6_data_1_MSbit_Addr 68
`define scan_in_inst_6_data_1_LSbit_Pos 2
`define scan_in_inst_6_data_1_MSbit_Pos 0
// Defines for register "scan_in_inst_7_data_1"
`define scan_in_inst_7_data_1_LSbit 545
`define scan_in_inst_7_data_1_MSbit 551
`define scan_in_inst_7_data_1_Sel 551:545
`define scan_in_inst_7_data_1_Width 7
`define scan_in_inst_7_data_1_LSbit_Addr 68
`define scan_in_inst_7_data_1_MSbit_Addr 68
`define scan_in_inst_7_data_1_LSbit_Pos 1
`define scan_in_inst_7_data_1_MSbit_Pos 7
// Defines for register "scan_in_inst_8_data_1"
`define scan_in_inst_8_data_1_LSbit 552
`define scan_in_inst_8_data_1_MSbit 558
`define scan_in_inst_8_data_1_Sel 558:552
`define scan_in_inst_8_data_1_Width 7
`define scan_in_inst_8_data_1_LSbit_Addr 69
`define scan_in_inst_8_data_1_MSbit_Addr 69
`define scan_in_inst_8_data_1_LSbit_Pos 0
`define scan_in_inst_8_data_1_MSbit_Pos 6
// Defines for register "scan_in_inst_9_data_1"
`define scan_in_inst_9_data_1_LSbit 559
`define scan_in_inst_9_data_1_MSbit 565
`define scan_in_inst_9_data_1_Sel 565:559
`define scan_in_inst_9_data_1_Width 7
`define scan_in_inst_9_data_1_LSbit_Addr 69
`define scan_in_inst_9_data_1_MSbit_Addr 70
`define scan_in_inst_9_data_1_LSbit_Pos 7
`define scan_in_inst_9_data_1_MSbit_Pos 5
// Defines for register "scan_in_inst_10_data_1"
`define scan_in_inst_10_data_1_LSbit 566
`define scan_in_inst_10_data_1_MSbit 572
`define scan_in_inst_10_data_1_Sel 572:566
`define scan_in_inst_10_data_1_Width 7
`define scan_in_inst_10_data_1_LSbit_Addr 70
`define scan_in_inst_10_data_1_MSbit_Addr 71
`define scan_in_inst_10_data_1_LSbit_Pos 6
`define scan_in_inst_10_data_1_MSbit_Pos 4
// Defines for register "scan_in_inst_11_data_1"
`define scan_in_inst_11_data_1_LSbit 573
`define scan_in_inst_11_data_1_MSbit 579
`define scan_in_inst_11_data_1_Sel 579:573
`define scan_in_inst_11_data_1_Width 7
`define scan_in_inst_11_data_1_LSbit_Addr 71
`define scan_in_inst_11_data_1_MSbit_Addr 72
`define scan_in_inst_11_data_1_LSbit_Pos 5
`define scan_in_inst_11_data_1_MSbit_Pos 3
// Defines for register "scan_in_inst_12_data_1"
`define scan_in_inst_12_data_1_LSbit 580
`define scan_in_inst_12_data_1_MSbit 586
`define scan_in_inst_12_data_1_Sel 586:580
`define scan_in_inst_12_data_1_Width 7
`define scan_in_inst_12_data_1_LSbit_Addr 72
`define scan_in_inst_12_data_1_MSbit_Addr 73
`define scan_in_inst_12_data_1_LSbit_Pos 4
`define scan_in_inst_12_data_1_MSbit_Pos 2
// Defines for register "scan_in_inst_13_data_1"
`define scan_in_inst_13_data_1_LSbit 587
`define scan_in_inst_13_data_1_MSbit 593
`define scan_in_inst_13_data_1_Sel 593:587
`define scan_in_inst_13_data_1_Width 7
`define scan_in_inst_13_data_1_LSbit_Addr 73
`define scan_in_inst_13_data_1_MSbit_Addr 74
`define scan_in_inst_13_data_1_LSbit_Pos 3
`define scan_in_inst_13_data_1_MSbit_Pos 1
// Defines for register "scan_in_inst_14_data_1"
`define scan_in_inst_14_data_1_LSbit 594
`define scan_in_inst_14_data_1_MSbit 600
`define scan_in_inst_14_data_1_Sel 600:594
`define scan_in_inst_14_data_1_Width 7
`define scan_in_inst_14_data_1_LSbit_Addr 74
`define scan_in_inst_14_data_1_MSbit_Addr 75
`define scan_in_inst_14_data_1_LSbit_Pos 2
`define scan_in_inst_14_data_1_MSbit_Pos 0
// Defines for register "scan_in_inst_15_data_1"
`define scan_in_inst_15_data_1_LSbit 601
`define scan_in_inst_15_data_1_MSbit 607
`define scan_in_inst_15_data_1_Sel 607:601
`define scan_in_inst_15_data_1_Width 7
`define scan_in_inst_15_data_1_LSbit_Addr 75
`define scan_in_inst_15_data_1_MSbit_Addr 75
`define scan_in_inst_15_data_1_LSbit_Pos 1
`define scan_in_inst_15_data_1_MSbit_Pos 7
// Defines for register "scan_in_inst_16_data_1"
`define scan_in_inst_16_data_1_LSbit 608
`define scan_in_inst_16_data_1_MSbit 614
`define scan_in_inst_16_data_1_Sel 614:608
`define scan_in_inst_16_data_1_Width 7
`define scan_in_inst_16_data_1_LSbit_Addr 76
`define scan_in_inst_16_data_1_MSbit_Addr 76
`define scan_in_inst_16_data_1_LSbit_Pos 0
`define scan_in_inst_16_data_1_MSbit_Pos 6
// Defines for register "scan_in_inst_17_data_1"
`define scan_in_inst_17_data_1_LSbit 615
`define scan_in_inst_17_data_1_MSbit 621
`define scan_in_inst_17_data_1_Sel 621:615
`define scan_in_inst_17_data_1_Width 7
`define scan_in_inst_17_data_1_LSbit_Addr 76
`define scan_in_inst_17_data_1_MSbit_Addr 77
`define scan_in_inst_17_data_1_LSbit_Pos 7
`define scan_in_inst_17_data_1_MSbit_Pos 5
// Defines for register "scan_in_inst_18_data_1"
`define scan_in_inst_18_data_1_LSbit 622
`define scan_in_inst_18_data_1_MSbit 628
`define scan_in_inst_18_data_1_Sel 628:622
`define scan_in_inst_18_data_1_Width 7
`define scan_in_inst_18_data_1_LSbit_Addr 77
`define scan_in_inst_18_data_1_MSbit_Addr 78
`define scan_in_inst_18_data_1_LSbit_Pos 6
`define scan_in_inst_18_data_1_MSbit_Pos 4
// Defines for register "scan_in_inst_19_data_1"
`define scan_in_inst_19_data_1_LSbit 629
`define scan_in_inst_19_data_1_MSbit 635
`define scan_in_inst_19_data_1_Sel 635:629
`define scan_in_inst_19_data_1_Width 7
`define scan_in_inst_19_data_1_LSbit_Addr 78
`define scan_in_inst_19_data_1_MSbit_Addr 79
`define scan_in_inst_19_data_1_LSbit_Pos 5
`define scan_in_inst_19_data_1_MSbit_Pos 3
// Defines for register "scan_in_inst_20_data_1"
`define scan_in_inst_20_data_1_LSbit 636
`define scan_in_inst_20_data_1_MSbit 642
`define scan_in_inst_20_data_1_Sel 642:636
`define scan_in_inst_20_data_1_Width 7
`define scan_in_inst_20_data_1_LSbit_Addr 79
`define scan_in_inst_20_data_1_MSbit_Addr 80
`define scan_in_inst_20_data_1_LSbit_Pos 4
`define scan_in_inst_20_data_1_MSbit_Pos 2
// Defines for register "scan_in_inst_21_data_1"
`define scan_in_inst_21_data_1_LSbit 643
`define scan_in_inst_21_data_1_MSbit 649
`define scan_in_inst_21_data_1_Sel 649:643
`define scan_in_inst_21_data_1_Width 7
`define scan_in_inst_21_data_1_LSbit_Addr 80
`define scan_in_inst_21_data_1_MSbit_Addr 81
`define scan_in_inst_21_data_1_LSbit_Pos 3
`define scan_in_inst_21_data_1_MSbit_Pos 1
// Defines for register "scan_in_inst_22_data_1"
`define scan_in_inst_22_data_1_LSbit 650
`define scan_in_inst_22_data_1_MSbit 656
`define scan_in_inst_22_data_1_Sel 656:650
`define scan_in_inst_22_data_1_Width 7
`define scan_in_inst_22_data_1_LSbit_Addr 81
`define scan_in_inst_22_data_1_MSbit_Addr 82
`define scan_in_inst_22_data_1_LSbit_Pos 2
`define scan_in_inst_22_data_1_MSbit_Pos 0
// Defines for register "scan_in_inst_23_data_1"
`define scan_in_inst_23_data_1_LSbit 657
`define scan_in_inst_23_data_1_MSbit 663
`define scan_in_inst_23_data_1_Sel 663:657
`define scan_in_inst_23_data_1_Width 7
`define scan_in_inst_23_data_1_LSbit_Addr 82
`define scan_in_inst_23_data_1_MSbit_Addr 82
`define scan_in_inst_23_data_1_LSbit_Pos 1
`define scan_in_inst_23_data_1_MSbit_Pos 7
// Defines for register "scan_in_inst_24_data_1"
`define scan_in_inst_24_data_1_LSbit 664
`define scan_in_inst_24_data_1_MSbit 670
`define scan_in_inst_24_data_1_Sel 670:664
`define scan_in_inst_24_data_1_Width 7
`define scan_in_inst_24_data_1_LSbit_Addr 83
`define scan_in_inst_24_data_1_MSbit_Addr 83
`define scan_in_inst_24_data_1_LSbit_Pos 0
`define scan_in_inst_24_data_1_MSbit_Pos 6
// Defines for register "scan_in_inst_25_data_1"
`define scan_in_inst_25_data_1_LSbit 671
`define scan_in_inst_25_data_1_MSbit 677
`define scan_in_inst_25_data_1_Sel 677:671
`define scan_in_inst_25_data_1_Width 7
`define scan_in_inst_25_data_1_LSbit_Addr 83
`define scan_in_inst_25_data_1_MSbit_Addr 84
`define scan_in_inst_25_data_1_LSbit_Pos 7
`define scan_in_inst_25_data_1_MSbit_Pos 5
// Defines for register "scan_in_inst_26_data_1"
`define scan_in_inst_26_data_1_LSbit 678
`define scan_in_inst_26_data_1_MSbit 684
`define scan_in_inst_26_data_1_Sel 684:678
`define scan_in_inst_26_data_1_Width 7
`define scan_in_inst_26_data_1_LSbit_Addr 84
`define scan_in_inst_26_data_1_MSbit_Addr 85
`define scan_in_inst_26_data_1_LSbit_Pos 6
`define scan_in_inst_26_data_1_MSbit_Pos 4
// Defines for register "scan_in_inst_27_data_1"
`define scan_in_inst_27_data_1_LSbit 685
`define scan_in_inst_27_data_1_MSbit 691
`define scan_in_inst_27_data_1_Sel 691:685
`define scan_in_inst_27_data_1_Width 7
`define scan_in_inst_27_data_1_LSbit_Addr 85
`define scan_in_inst_27_data_1_MSbit_Addr 86
`define scan_in_inst_27_data_1_LSbit_Pos 5
`define scan_in_inst_27_data_1_MSbit_Pos 3
// Defines for register "scan_in_inst_28_data_1"
`define scan_in_inst_28_data_1_LSbit 692
`define scan_in_inst_28_data_1_MSbit 698
`define scan_in_inst_28_data_1_Sel 698:692
`define scan_in_inst_28_data_1_Width 7
`define scan_in_inst_28_data_1_LSbit_Addr 86
`define scan_in_inst_28_data_1_MSbit_Addr 87
`define scan_in_inst_28_data_1_LSbit_Pos 4
`define scan_in_inst_28_data_1_MSbit_Pos 2
// Defines for register "scan_in_inst_29_data_1"
`define scan_in_inst_29_data_1_LSbit 699
`define scan_in_inst_29_data_1_MSbit 705
`define scan_in_inst_29_data_1_Sel 705:699
`define scan_in_inst_29_data_1_Width 7
`define scan_in_inst_29_data_1_LSbit_Addr 87
`define scan_in_inst_29_data_1_MSbit_Addr 88
`define scan_in_inst_29_data_1_LSbit_Pos 3
`define scan_in_inst_29_data_1_MSbit_Pos 1
// Defines for register "scan_in_inst_30_data_1"
`define scan_in_inst_30_data_1_LSbit 706
`define scan_in_inst_30_data_1_MSbit 712
`define scan_in_inst_30_data_1_Sel 712:706
`define scan_in_inst_30_data_1_Width 7
`define scan_in_inst_30_data_1_LSbit_Addr 88
`define scan_in_inst_30_data_1_MSbit_Addr 89
`define scan_in_inst_30_data_1_LSbit_Pos 2
`define scan_in_inst_30_data_1_MSbit_Pos 0
// Defines for register "scan_in_inst_31_data_1"
`define scan_in_inst_31_data_1_LSbit 713
`define scan_in_inst_31_data_1_MSbit 719
`define scan_in_inst_31_data_1_Sel 719:713
`define scan_in_inst_31_data_1_Width 7
`define scan_in_inst_31_data_1_LSbit_Addr 89
`define scan_in_inst_31_data_1_MSbit_Addr 89
`define scan_in_inst_31_data_1_LSbit_Pos 1
`define scan_in_inst_31_data_1_MSbit_Pos 7
// Defines for register "scan_in_inst_req_1"
`define scan_in_inst_req_1_LSbit 720
`define scan_in_inst_req_1_MSbit 720
`define scan_in_inst_req_1_Sel 720:720
`define scan_in_inst_req_1_Width 1
`define scan_in_inst_req_1_LSbit_Addr 90
`define scan_in_inst_req_1_MSbit_Addr 90
`define scan_in_inst_req_1_LSbit_Pos 0
`define scan_in_inst_req_1_MSbit_Pos 0
// Defines for register "scan_in_inst_cmd_1"
`define scan_in_inst_cmd_1_LSbit 721
`define scan_in_inst_cmd_1_MSbit 722
`define scan_in_inst_cmd_1_Sel 722:721
`define scan_in_inst_cmd_1_Width 2
`define scan_in_inst_cmd_1_LSbit_Addr 90
`define scan_in_inst_cmd_1_MSbit_Addr 90
`define scan_in_inst_cmd_1_LSbit_Pos 1
`define scan_in_inst_cmd_1_MSbit_Pos 2
// Defines for register "scan_in_inst_ack_1"
`define scan_in_inst_ack_1_LSbit 723
`define scan_in_inst_ack_1_MSbit 723
`define scan_in_inst_ack_1_Sel 723:723
`define scan_in_inst_ack_1_Width 1
`define scan_in_inst_ack_1_LSbit_Addr 90
`define scan_in_inst_ack_1_MSbit_Addr 90
`define scan_in_inst_ack_1_LSbit_Pos 3
`define scan_in_inst_ack_1_MSbit_Pos 3
// Field INSTRUCTION_1 length
`define INSTRUCTION_1_field_bit_length 228
`define INSTRUCTION_1_field_byte_length 29

/************************/
/* Field: INSTRUCTION_2 */
/************************/
`define INSTRUCTION_2_field_addr 91
// Defines for register "scan_in_inst_0_data_2"
`define scan_in_inst_0_data_2_LSbit 728
`define scan_in_inst_0_data_2_MSbit 734
`define scan_in_inst_0_data_2_Sel 734:728
`define scan_in_inst_0_data_2_Width 7
`define scan_in_inst_0_data_2_LSbit_Addr 91
`define scan_in_inst_0_data_2_MSbit_Addr 91
`define scan_in_inst_0_data_2_LSbit_Pos 0
`define scan_in_inst_0_data_2_MSbit_Pos 6
// Defines for register "scan_in_inst_1_data_2"
`define scan_in_inst_1_data_2_LSbit 735
`define scan_in_inst_1_data_2_MSbit 741
`define scan_in_inst_1_data_2_Sel 741:735
`define scan_in_inst_1_data_2_Width 7
`define scan_in_inst_1_data_2_LSbit_Addr 91
`define scan_in_inst_1_data_2_MSbit_Addr 92
`define scan_in_inst_1_data_2_LSbit_Pos 7
`define scan_in_inst_1_data_2_MSbit_Pos 5
// Defines for register "scan_in_inst_2_data_2"
`define scan_in_inst_2_data_2_LSbit 742
`define scan_in_inst_2_data_2_MSbit 748
`define scan_in_inst_2_data_2_Sel 748:742
`define scan_in_inst_2_data_2_Width 7
`define scan_in_inst_2_data_2_LSbit_Addr 92
`define scan_in_inst_2_data_2_MSbit_Addr 93
`define scan_in_inst_2_data_2_LSbit_Pos 6
`define scan_in_inst_2_data_2_MSbit_Pos 4
// Defines for register "scan_in_inst_3_data_2"
`define scan_in_inst_3_data_2_LSbit 749
`define scan_in_inst_3_data_2_MSbit 755
`define scan_in_inst_3_data_2_Sel 755:749
`define scan_in_inst_3_data_2_Width 7
`define scan_in_inst_3_data_2_LSbit_Addr 93
`define scan_in_inst_3_data_2_MSbit_Addr 94
`define scan_in_inst_3_data_2_LSbit_Pos 5
`define scan_in_inst_3_data_2_MSbit_Pos 3
// Defines for register "scan_in_inst_4_data_2"
`define scan_in_inst_4_data_2_LSbit 756
`define scan_in_inst_4_data_2_MSbit 762
`define scan_in_inst_4_data_2_Sel 762:756
`define scan_in_inst_4_data_2_Width 7
`define scan_in_inst_4_data_2_LSbit_Addr 94
`define scan_in_inst_4_data_2_MSbit_Addr 95
`define scan_in_inst_4_data_2_LSbit_Pos 4
`define scan_in_inst_4_data_2_MSbit_Pos 2
// Defines for register "scan_in_inst_5_data_2"
`define scan_in_inst_5_data_2_LSbit 763
`define scan_in_inst_5_data_2_MSbit 769
`define scan_in_inst_5_data_2_Sel 769:763
`define scan_in_inst_5_data_2_Width 7
`define scan_in_inst_5_data_2_LSbit_Addr 95
`define scan_in_inst_5_data_2_MSbit_Addr 96
`define scan_in_inst_5_data_2_LSbit_Pos 3
`define scan_in_inst_5_data_2_MSbit_Pos 1
// Defines for register "scan_in_inst_6_data_2"
`define scan_in_inst_6_data_2_LSbit 770
`define scan_in_inst_6_data_2_MSbit 776
`define scan_in_inst_6_data_2_Sel 776:770
`define scan_in_inst_6_data_2_Width 7
`define scan_in_inst_6_data_2_LSbit_Addr 96
`define scan_in_inst_6_data_2_MSbit_Addr 97
`define scan_in_inst_6_data_2_LSbit_Pos 2
`define scan_in_inst_6_data_2_MSbit_Pos 0
// Defines for register "scan_in_inst_7_data_2"
`define scan_in_inst_7_data_2_LSbit 777
`define scan_in_inst_7_data_2_MSbit 783
`define scan_in_inst_7_data_2_Sel 783:777
`define scan_in_inst_7_data_2_Width 7
`define scan_in_inst_7_data_2_LSbit_Addr 97
`define scan_in_inst_7_data_2_MSbit_Addr 97
`define scan_in_inst_7_data_2_LSbit_Pos 1
`define scan_in_inst_7_data_2_MSbit_Pos 7
// Defines for register "scan_in_inst_8_data_2"
`define scan_in_inst_8_data_2_LSbit 784
`define scan_in_inst_8_data_2_MSbit 790
`define scan_in_inst_8_data_2_Sel 790:784
`define scan_in_inst_8_data_2_Width 7
`define scan_in_inst_8_data_2_LSbit_Addr 98
`define scan_in_inst_8_data_2_MSbit_Addr 98
`define scan_in_inst_8_data_2_LSbit_Pos 0
`define scan_in_inst_8_data_2_MSbit_Pos 6
// Defines for register "scan_in_inst_9_data_2"
`define scan_in_inst_9_data_2_LSbit 791
`define scan_in_inst_9_data_2_MSbit 797
`define scan_in_inst_9_data_2_Sel 797:791
`define scan_in_inst_9_data_2_Width 7
`define scan_in_inst_9_data_2_LSbit_Addr 98
`define scan_in_inst_9_data_2_MSbit_Addr 99
`define scan_in_inst_9_data_2_LSbit_Pos 7
`define scan_in_inst_9_data_2_MSbit_Pos 5
// Defines for register "scan_in_inst_10_data_2"
`define scan_in_inst_10_data_2_LSbit 798
`define scan_in_inst_10_data_2_MSbit 804
`define scan_in_inst_10_data_2_Sel 804:798
`define scan_in_inst_10_data_2_Width 7
`define scan_in_inst_10_data_2_LSbit_Addr 99
`define scan_in_inst_10_data_2_MSbit_Addr 100
`define scan_in_inst_10_data_2_LSbit_Pos 6
`define scan_in_inst_10_data_2_MSbit_Pos 4
// Defines for register "scan_in_inst_11_data_2"
`define scan_in_inst_11_data_2_LSbit 805
`define scan_in_inst_11_data_2_MSbit 811
`define scan_in_inst_11_data_2_Sel 811:805
`define scan_in_inst_11_data_2_Width 7
`define scan_in_inst_11_data_2_LSbit_Addr 100
`define scan_in_inst_11_data_2_MSbit_Addr 101
`define scan_in_inst_11_data_2_LSbit_Pos 5
`define scan_in_inst_11_data_2_MSbit_Pos 3
// Defines for register "scan_in_inst_12_data_2"
`define scan_in_inst_12_data_2_LSbit 812
`define scan_in_inst_12_data_2_MSbit 818
`define scan_in_inst_12_data_2_Sel 818:812
`define scan_in_inst_12_data_2_Width 7
`define scan_in_inst_12_data_2_LSbit_Addr 101
`define scan_in_inst_12_data_2_MSbit_Addr 102
`define scan_in_inst_12_data_2_LSbit_Pos 4
`define scan_in_inst_12_data_2_MSbit_Pos 2
// Defines for register "scan_in_inst_13_data_2"
`define scan_in_inst_13_data_2_LSbit 819
`define scan_in_inst_13_data_2_MSbit 825
`define scan_in_inst_13_data_2_Sel 825:819
`define scan_in_inst_13_data_2_Width 7
`define scan_in_inst_13_data_2_LSbit_Addr 102
`define scan_in_inst_13_data_2_MSbit_Addr 103
`define scan_in_inst_13_data_2_LSbit_Pos 3
`define scan_in_inst_13_data_2_MSbit_Pos 1
// Defines for register "scan_in_inst_14_data_2"
`define scan_in_inst_14_data_2_LSbit 826
`define scan_in_inst_14_data_2_MSbit 832
`define scan_in_inst_14_data_2_Sel 832:826
`define scan_in_inst_14_data_2_Width 7
`define scan_in_inst_14_data_2_LSbit_Addr 103
`define scan_in_inst_14_data_2_MSbit_Addr 104
`define scan_in_inst_14_data_2_LSbit_Pos 2
`define scan_in_inst_14_data_2_MSbit_Pos 0
// Defines for register "scan_in_inst_15_data_2"
`define scan_in_inst_15_data_2_LSbit 833
`define scan_in_inst_15_data_2_MSbit 839
`define scan_in_inst_15_data_2_Sel 839:833
`define scan_in_inst_15_data_2_Width 7
`define scan_in_inst_15_data_2_LSbit_Addr 104
`define scan_in_inst_15_data_2_MSbit_Addr 104
`define scan_in_inst_15_data_2_LSbit_Pos 1
`define scan_in_inst_15_data_2_MSbit_Pos 7
// Defines for register "scan_in_inst_16_data_2"
`define scan_in_inst_16_data_2_LSbit 840
`define scan_in_inst_16_data_2_MSbit 846
`define scan_in_inst_16_data_2_Sel 846:840
`define scan_in_inst_16_data_2_Width 7
`define scan_in_inst_16_data_2_LSbit_Addr 105
`define scan_in_inst_16_data_2_MSbit_Addr 105
`define scan_in_inst_16_data_2_LSbit_Pos 0
`define scan_in_inst_16_data_2_MSbit_Pos 6
// Defines for register "scan_in_inst_17_data_2"
`define scan_in_inst_17_data_2_LSbit 847
`define scan_in_inst_17_data_2_MSbit 853
`define scan_in_inst_17_data_2_Sel 853:847
`define scan_in_inst_17_data_2_Width 7
`define scan_in_inst_17_data_2_LSbit_Addr 105
`define scan_in_inst_17_data_2_MSbit_Addr 106
`define scan_in_inst_17_data_2_LSbit_Pos 7
`define scan_in_inst_17_data_2_MSbit_Pos 5
// Defines for register "scan_in_inst_18_data_2"
`define scan_in_inst_18_data_2_LSbit 854
`define scan_in_inst_18_data_2_MSbit 860
`define scan_in_inst_18_data_2_Sel 860:854
`define scan_in_inst_18_data_2_Width 7
`define scan_in_inst_18_data_2_LSbit_Addr 106
`define scan_in_inst_18_data_2_MSbit_Addr 107
`define scan_in_inst_18_data_2_LSbit_Pos 6
`define scan_in_inst_18_data_2_MSbit_Pos 4
// Defines for register "scan_in_inst_19_data_2"
`define scan_in_inst_19_data_2_LSbit 861
`define scan_in_inst_19_data_2_MSbit 867
`define scan_in_inst_19_data_2_Sel 867:861
`define scan_in_inst_19_data_2_Width 7
`define scan_in_inst_19_data_2_LSbit_Addr 107
`define scan_in_inst_19_data_2_MSbit_Addr 108
`define scan_in_inst_19_data_2_LSbit_Pos 5
`define scan_in_inst_19_data_2_MSbit_Pos 3
// Defines for register "scan_in_inst_20_data_2"
`define scan_in_inst_20_data_2_LSbit 868
`define scan_in_inst_20_data_2_MSbit 874
`define scan_in_inst_20_data_2_Sel 874:868
`define scan_in_inst_20_data_2_Width 7
`define scan_in_inst_20_data_2_LSbit_Addr 108
`define scan_in_inst_20_data_2_MSbit_Addr 109
`define scan_in_inst_20_data_2_LSbit_Pos 4
`define scan_in_inst_20_data_2_MSbit_Pos 2
// Defines for register "scan_in_inst_21_data_2"
`define scan_in_inst_21_data_2_LSbit 875
`define scan_in_inst_21_data_2_MSbit 881
`define scan_in_inst_21_data_2_Sel 881:875
`define scan_in_inst_21_data_2_Width 7
`define scan_in_inst_21_data_2_LSbit_Addr 109
`define scan_in_inst_21_data_2_MSbit_Addr 110
`define scan_in_inst_21_data_2_LSbit_Pos 3
`define scan_in_inst_21_data_2_MSbit_Pos 1
// Defines for register "scan_in_inst_22_data_2"
`define scan_in_inst_22_data_2_LSbit 882
`define scan_in_inst_22_data_2_MSbit 888
`define scan_in_inst_22_data_2_Sel 888:882
`define scan_in_inst_22_data_2_Width 7
`define scan_in_inst_22_data_2_LSbit_Addr 110
`define scan_in_inst_22_data_2_MSbit_Addr 111
`define scan_in_inst_22_data_2_LSbit_Pos 2
`define scan_in_inst_22_data_2_MSbit_Pos 0
// Defines for register "scan_in_inst_23_data_2"
`define scan_in_inst_23_data_2_LSbit 889
`define scan_in_inst_23_data_2_MSbit 895
`define scan_in_inst_23_data_2_Sel 895:889
`define scan_in_inst_23_data_2_Width 7
`define scan_in_inst_23_data_2_LSbit_Addr 111
`define scan_in_inst_23_data_2_MSbit_Addr 111
`define scan_in_inst_23_data_2_LSbit_Pos 1
`define scan_in_inst_23_data_2_MSbit_Pos 7
// Defines for register "scan_in_inst_24_data_2"
`define scan_in_inst_24_data_2_LSbit 896
`define scan_in_inst_24_data_2_MSbit 902
`define scan_in_inst_24_data_2_Sel 902:896
`define scan_in_inst_24_data_2_Width 7
`define scan_in_inst_24_data_2_LSbit_Addr 112
`define scan_in_inst_24_data_2_MSbit_Addr 112
`define scan_in_inst_24_data_2_LSbit_Pos 0
`define scan_in_inst_24_data_2_MSbit_Pos 6
// Defines for register "scan_in_inst_25_data_2"
`define scan_in_inst_25_data_2_LSbit 903
`define scan_in_inst_25_data_2_MSbit 909
`define scan_in_inst_25_data_2_Sel 909:903
`define scan_in_inst_25_data_2_Width 7
`define scan_in_inst_25_data_2_LSbit_Addr 112
`define scan_in_inst_25_data_2_MSbit_Addr 113
`define scan_in_inst_25_data_2_LSbit_Pos 7
`define scan_in_inst_25_data_2_MSbit_Pos 5
// Defines for register "scan_in_inst_26_data_2"
`define scan_in_inst_26_data_2_LSbit 910
`define scan_in_inst_26_data_2_MSbit 916
`define scan_in_inst_26_data_2_Sel 916:910
`define scan_in_inst_26_data_2_Width 7
`define scan_in_inst_26_data_2_LSbit_Addr 113
`define scan_in_inst_26_data_2_MSbit_Addr 114
`define scan_in_inst_26_data_2_LSbit_Pos 6
`define scan_in_inst_26_data_2_MSbit_Pos 4
// Defines for register "scan_in_inst_27_data_2"
`define scan_in_inst_27_data_2_LSbit 917
`define scan_in_inst_27_data_2_MSbit 923
`define scan_in_inst_27_data_2_Sel 923:917
`define scan_in_inst_27_data_2_Width 7
`define scan_in_inst_27_data_2_LSbit_Addr 114
`define scan_in_inst_27_data_2_MSbit_Addr 115
`define scan_in_inst_27_data_2_LSbit_Pos 5
`define scan_in_inst_27_data_2_MSbit_Pos 3
// Defines for register "scan_in_inst_28_data_2"
`define scan_in_inst_28_data_2_LSbit 924
`define scan_in_inst_28_data_2_MSbit 930
`define scan_in_inst_28_data_2_Sel 930:924
`define scan_in_inst_28_data_2_Width 7
`define scan_in_inst_28_data_2_LSbit_Addr 115
`define scan_in_inst_28_data_2_MSbit_Addr 116
`define scan_in_inst_28_data_2_LSbit_Pos 4
`define scan_in_inst_28_data_2_MSbit_Pos 2
// Defines for register "scan_in_inst_29_data_2"
`define scan_in_inst_29_data_2_LSbit 931
`define scan_in_inst_29_data_2_MSbit 937
`define scan_in_inst_29_data_2_Sel 937:931
`define scan_in_inst_29_data_2_Width 7
`define scan_in_inst_29_data_2_LSbit_Addr 116
`define scan_in_inst_29_data_2_MSbit_Addr 117
`define scan_in_inst_29_data_2_LSbit_Pos 3
`define scan_in_inst_29_data_2_MSbit_Pos 1
// Defines for register "scan_in_inst_30_data_2"
`define scan_in_inst_30_data_2_LSbit 938
`define scan_in_inst_30_data_2_MSbit 944
`define scan_in_inst_30_data_2_Sel 944:938
`define scan_in_inst_30_data_2_Width 7
`define scan_in_inst_30_data_2_LSbit_Addr 117
`define scan_in_inst_30_data_2_MSbit_Addr 118
`define scan_in_inst_30_data_2_LSbit_Pos 2
`define scan_in_inst_30_data_2_MSbit_Pos 0
// Defines for register "scan_in_inst_31_data_2"
`define scan_in_inst_31_data_2_LSbit 945
`define scan_in_inst_31_data_2_MSbit 951
`define scan_in_inst_31_data_2_Sel 951:945
`define scan_in_inst_31_data_2_Width 7
`define scan_in_inst_31_data_2_LSbit_Addr 118
`define scan_in_inst_31_data_2_MSbit_Addr 118
`define scan_in_inst_31_data_2_LSbit_Pos 1
`define scan_in_inst_31_data_2_MSbit_Pos 7
// Defines for register "scan_in_inst_req_2"
`define scan_in_inst_req_2_LSbit 952
`define scan_in_inst_req_2_MSbit 952
`define scan_in_inst_req_2_Sel 952:952
`define scan_in_inst_req_2_Width 1
`define scan_in_inst_req_2_LSbit_Addr 119
`define scan_in_inst_req_2_MSbit_Addr 119
`define scan_in_inst_req_2_LSbit_Pos 0
`define scan_in_inst_req_2_MSbit_Pos 0
// Defines for register "scan_in_inst_cmd_2"
`define scan_in_inst_cmd_2_LSbit 953
`define scan_in_inst_cmd_2_MSbit 954
`define scan_in_inst_cmd_2_Sel 954:953
`define scan_in_inst_cmd_2_Width 2
`define scan_in_inst_cmd_2_LSbit_Addr 119
`define scan_in_inst_cmd_2_MSbit_Addr 119
`define scan_in_inst_cmd_2_LSbit_Pos 1
`define scan_in_inst_cmd_2_MSbit_Pos 2
// Defines for register "scan_in_inst_ack_2"
`define scan_in_inst_ack_2_LSbit 955
`define scan_in_inst_ack_2_MSbit 955
`define scan_in_inst_ack_2_Sel 955:955
`define scan_in_inst_ack_2_Width 1
`define scan_in_inst_ack_2_LSbit_Addr 119
`define scan_in_inst_ack_2_MSbit_Addr 119
`define scan_in_inst_ack_2_LSbit_Pos 3
`define scan_in_inst_ack_2_MSbit_Pos 3
// Field INSTRUCTION_2 length
`define INSTRUCTION_2_field_bit_length 228
`define INSTRUCTION_2_field_byte_length 29

/************************/
/* Field: INSTRUCTION_3 */
/************************/
`define INSTRUCTION_3_field_addr 120
// Defines for register "scan_in_inst_0_data_3"
`define scan_in_inst_0_data_3_LSbit 960
`define scan_in_inst_0_data_3_MSbit 966
`define scan_in_inst_0_data_3_Sel 966:960
`define scan_in_inst_0_data_3_Width 7
`define scan_in_inst_0_data_3_LSbit_Addr 120
`define scan_in_inst_0_data_3_MSbit_Addr 120
`define scan_in_inst_0_data_3_LSbit_Pos 0
`define scan_in_inst_0_data_3_MSbit_Pos 6
// Defines for register "scan_in_inst_1_data_3"
`define scan_in_inst_1_data_3_LSbit 967
`define scan_in_inst_1_data_3_MSbit 973
`define scan_in_inst_1_data_3_Sel 973:967
`define scan_in_inst_1_data_3_Width 7
`define scan_in_inst_1_data_3_LSbit_Addr 120
`define scan_in_inst_1_data_3_MSbit_Addr 121
`define scan_in_inst_1_data_3_LSbit_Pos 7
`define scan_in_inst_1_data_3_MSbit_Pos 5
// Defines for register "scan_in_inst_2_data_3"
`define scan_in_inst_2_data_3_LSbit 974
`define scan_in_inst_2_data_3_MSbit 980
`define scan_in_inst_2_data_3_Sel 980:974
`define scan_in_inst_2_data_3_Width 7
`define scan_in_inst_2_data_3_LSbit_Addr 121
`define scan_in_inst_2_data_3_MSbit_Addr 122
`define scan_in_inst_2_data_3_LSbit_Pos 6
`define scan_in_inst_2_data_3_MSbit_Pos 4
// Defines for register "scan_in_inst_3_data_3"
`define scan_in_inst_3_data_3_LSbit 981
`define scan_in_inst_3_data_3_MSbit 987
`define scan_in_inst_3_data_3_Sel 987:981
`define scan_in_inst_3_data_3_Width 7
`define scan_in_inst_3_data_3_LSbit_Addr 122
`define scan_in_inst_3_data_3_MSbit_Addr 123
`define scan_in_inst_3_data_3_LSbit_Pos 5
`define scan_in_inst_3_data_3_MSbit_Pos 3
// Defines for register "scan_in_inst_4_data_3"
`define scan_in_inst_4_data_3_LSbit 988
`define scan_in_inst_4_data_3_MSbit 994
`define scan_in_inst_4_data_3_Sel 994:988
`define scan_in_inst_4_data_3_Width 7
`define scan_in_inst_4_data_3_LSbit_Addr 123
`define scan_in_inst_4_data_3_MSbit_Addr 124
`define scan_in_inst_4_data_3_LSbit_Pos 4
`define scan_in_inst_4_data_3_MSbit_Pos 2
// Defines for register "scan_in_inst_5_data_3"
`define scan_in_inst_5_data_3_LSbit 995
`define scan_in_inst_5_data_3_MSbit 1001
`define scan_in_inst_5_data_3_Sel 1001:995
`define scan_in_inst_5_data_3_Width 7
`define scan_in_inst_5_data_3_LSbit_Addr 124
`define scan_in_inst_5_data_3_MSbit_Addr 125
`define scan_in_inst_5_data_3_LSbit_Pos 3
`define scan_in_inst_5_data_3_MSbit_Pos 1
// Defines for register "scan_in_inst_6_data_3"
`define scan_in_inst_6_data_3_LSbit 1002
`define scan_in_inst_6_data_3_MSbit 1008
`define scan_in_inst_6_data_3_Sel 1008:1002
`define scan_in_inst_6_data_3_Width 7
`define scan_in_inst_6_data_3_LSbit_Addr 125
`define scan_in_inst_6_data_3_MSbit_Addr 126
`define scan_in_inst_6_data_3_LSbit_Pos 2
`define scan_in_inst_6_data_3_MSbit_Pos 0
// Defines for register "scan_in_inst_7_data_3"
`define scan_in_inst_7_data_3_LSbit 1009
`define scan_in_inst_7_data_3_MSbit 1015
`define scan_in_inst_7_data_3_Sel 1015:1009
`define scan_in_inst_7_data_3_Width 7
`define scan_in_inst_7_data_3_LSbit_Addr 126
`define scan_in_inst_7_data_3_MSbit_Addr 126
`define scan_in_inst_7_data_3_LSbit_Pos 1
`define scan_in_inst_7_data_3_MSbit_Pos 7
// Defines for register "scan_in_inst_8_data_3"
`define scan_in_inst_8_data_3_LSbit 1016
`define scan_in_inst_8_data_3_MSbit 1022
`define scan_in_inst_8_data_3_Sel 1022:1016
`define scan_in_inst_8_data_3_Width 7
`define scan_in_inst_8_data_3_LSbit_Addr 127
`define scan_in_inst_8_data_3_MSbit_Addr 127
`define scan_in_inst_8_data_3_LSbit_Pos 0
`define scan_in_inst_8_data_3_MSbit_Pos 6
// Defines for register "scan_in_inst_9_data_3"
`define scan_in_inst_9_data_3_LSbit 1023
`define scan_in_inst_9_data_3_MSbit 1029
`define scan_in_inst_9_data_3_Sel 1029:1023
`define scan_in_inst_9_data_3_Width 7
`define scan_in_inst_9_data_3_LSbit_Addr 127
`define scan_in_inst_9_data_3_MSbit_Addr 128
`define scan_in_inst_9_data_3_LSbit_Pos 7
`define scan_in_inst_9_data_3_MSbit_Pos 5
// Defines for register "scan_in_inst_10_data_3"
`define scan_in_inst_10_data_3_LSbit 1030
`define scan_in_inst_10_data_3_MSbit 1036
`define scan_in_inst_10_data_3_Sel 1036:1030
`define scan_in_inst_10_data_3_Width 7
`define scan_in_inst_10_data_3_LSbit_Addr 128
`define scan_in_inst_10_data_3_MSbit_Addr 129
`define scan_in_inst_10_data_3_LSbit_Pos 6
`define scan_in_inst_10_data_3_MSbit_Pos 4
// Defines for register "scan_in_inst_11_data_3"
`define scan_in_inst_11_data_3_LSbit 1037
`define scan_in_inst_11_data_3_MSbit 1043
`define scan_in_inst_11_data_3_Sel 1043:1037
`define scan_in_inst_11_data_3_Width 7
`define scan_in_inst_11_data_3_LSbit_Addr 129
`define scan_in_inst_11_data_3_MSbit_Addr 130
`define scan_in_inst_11_data_3_LSbit_Pos 5
`define scan_in_inst_11_data_3_MSbit_Pos 3
// Defines for register "scan_in_inst_12_data_3"
`define scan_in_inst_12_data_3_LSbit 1044
`define scan_in_inst_12_data_3_MSbit 1050
`define scan_in_inst_12_data_3_Sel 1050:1044
`define scan_in_inst_12_data_3_Width 7
`define scan_in_inst_12_data_3_LSbit_Addr 130
`define scan_in_inst_12_data_3_MSbit_Addr 131
`define scan_in_inst_12_data_3_LSbit_Pos 4
`define scan_in_inst_12_data_3_MSbit_Pos 2
// Defines for register "scan_in_inst_13_data_3"
`define scan_in_inst_13_data_3_LSbit 1051
`define scan_in_inst_13_data_3_MSbit 1057
`define scan_in_inst_13_data_3_Sel 1057:1051
`define scan_in_inst_13_data_3_Width 7
`define scan_in_inst_13_data_3_LSbit_Addr 131
`define scan_in_inst_13_data_3_MSbit_Addr 132
`define scan_in_inst_13_data_3_LSbit_Pos 3
`define scan_in_inst_13_data_3_MSbit_Pos 1
// Defines for register "scan_in_inst_14_data_3"
`define scan_in_inst_14_data_3_LSbit 1058
`define scan_in_inst_14_data_3_MSbit 1064
`define scan_in_inst_14_data_3_Sel 1064:1058
`define scan_in_inst_14_data_3_Width 7
`define scan_in_inst_14_data_3_LSbit_Addr 132
`define scan_in_inst_14_data_3_MSbit_Addr 133
`define scan_in_inst_14_data_3_LSbit_Pos 2
`define scan_in_inst_14_data_3_MSbit_Pos 0
// Defines for register "scan_in_inst_15_data_3"
`define scan_in_inst_15_data_3_LSbit 1065
`define scan_in_inst_15_data_3_MSbit 1071
`define scan_in_inst_15_data_3_Sel 1071:1065
`define scan_in_inst_15_data_3_Width 7
`define scan_in_inst_15_data_3_LSbit_Addr 133
`define scan_in_inst_15_data_3_MSbit_Addr 133
`define scan_in_inst_15_data_3_LSbit_Pos 1
`define scan_in_inst_15_data_3_MSbit_Pos 7
// Defines for register "scan_in_inst_16_data_3"
`define scan_in_inst_16_data_3_LSbit 1072
`define scan_in_inst_16_data_3_MSbit 1078
`define scan_in_inst_16_data_3_Sel 1078:1072
`define scan_in_inst_16_data_3_Width 7
`define scan_in_inst_16_data_3_LSbit_Addr 134
`define scan_in_inst_16_data_3_MSbit_Addr 134
`define scan_in_inst_16_data_3_LSbit_Pos 0
`define scan_in_inst_16_data_3_MSbit_Pos 6
// Defines for register "scan_in_inst_17_data_3"
`define scan_in_inst_17_data_3_LSbit 1079
`define scan_in_inst_17_data_3_MSbit 1085
`define scan_in_inst_17_data_3_Sel 1085:1079
`define scan_in_inst_17_data_3_Width 7
`define scan_in_inst_17_data_3_LSbit_Addr 134
`define scan_in_inst_17_data_3_MSbit_Addr 135
`define scan_in_inst_17_data_3_LSbit_Pos 7
`define scan_in_inst_17_data_3_MSbit_Pos 5
// Defines for register "scan_in_inst_18_data_3"
`define scan_in_inst_18_data_3_LSbit 1086
`define scan_in_inst_18_data_3_MSbit 1092
`define scan_in_inst_18_data_3_Sel 1092:1086
`define scan_in_inst_18_data_3_Width 7
`define scan_in_inst_18_data_3_LSbit_Addr 135
`define scan_in_inst_18_data_3_MSbit_Addr 136
`define scan_in_inst_18_data_3_LSbit_Pos 6
`define scan_in_inst_18_data_3_MSbit_Pos 4
// Defines for register "scan_in_inst_19_data_3"
`define scan_in_inst_19_data_3_LSbit 1093
`define scan_in_inst_19_data_3_MSbit 1099
`define scan_in_inst_19_data_3_Sel 1099:1093
`define scan_in_inst_19_data_3_Width 7
`define scan_in_inst_19_data_3_LSbit_Addr 136
`define scan_in_inst_19_data_3_MSbit_Addr 137
`define scan_in_inst_19_data_3_LSbit_Pos 5
`define scan_in_inst_19_data_3_MSbit_Pos 3
// Defines for register "scan_in_inst_20_data_3"
`define scan_in_inst_20_data_3_LSbit 1100
`define scan_in_inst_20_data_3_MSbit 1106
`define scan_in_inst_20_data_3_Sel 1106:1100
`define scan_in_inst_20_data_3_Width 7
`define scan_in_inst_20_data_3_LSbit_Addr 137
`define scan_in_inst_20_data_3_MSbit_Addr 138
`define scan_in_inst_20_data_3_LSbit_Pos 4
`define scan_in_inst_20_data_3_MSbit_Pos 2
// Defines for register "scan_in_inst_21_data_3"
`define scan_in_inst_21_data_3_LSbit 1107
`define scan_in_inst_21_data_3_MSbit 1113
`define scan_in_inst_21_data_3_Sel 1113:1107
`define scan_in_inst_21_data_3_Width 7
`define scan_in_inst_21_data_3_LSbit_Addr 138
`define scan_in_inst_21_data_3_MSbit_Addr 139
`define scan_in_inst_21_data_3_LSbit_Pos 3
`define scan_in_inst_21_data_3_MSbit_Pos 1
// Defines for register "scan_in_inst_22_data_3"
`define scan_in_inst_22_data_3_LSbit 1114
`define scan_in_inst_22_data_3_MSbit 1120
`define scan_in_inst_22_data_3_Sel 1120:1114
`define scan_in_inst_22_data_3_Width 7
`define scan_in_inst_22_data_3_LSbit_Addr 139
`define scan_in_inst_22_data_3_MSbit_Addr 140
`define scan_in_inst_22_data_3_LSbit_Pos 2
`define scan_in_inst_22_data_3_MSbit_Pos 0
// Defines for register "scan_in_inst_23_data_3"
`define scan_in_inst_23_data_3_LSbit 1121
`define scan_in_inst_23_data_3_MSbit 1127
`define scan_in_inst_23_data_3_Sel 1127:1121
`define scan_in_inst_23_data_3_Width 7
`define scan_in_inst_23_data_3_LSbit_Addr 140
`define scan_in_inst_23_data_3_MSbit_Addr 140
`define scan_in_inst_23_data_3_LSbit_Pos 1
`define scan_in_inst_23_data_3_MSbit_Pos 7
// Defines for register "scan_in_inst_24_data_3"
`define scan_in_inst_24_data_3_LSbit 1128
`define scan_in_inst_24_data_3_MSbit 1134
`define scan_in_inst_24_data_3_Sel 1134:1128
`define scan_in_inst_24_data_3_Width 7
`define scan_in_inst_24_data_3_LSbit_Addr 141
`define scan_in_inst_24_data_3_MSbit_Addr 141
`define scan_in_inst_24_data_3_LSbit_Pos 0
`define scan_in_inst_24_data_3_MSbit_Pos 6
// Defines for register "scan_in_inst_25_data_3"
`define scan_in_inst_25_data_3_LSbit 1135
`define scan_in_inst_25_data_3_MSbit 1141
`define scan_in_inst_25_data_3_Sel 1141:1135
`define scan_in_inst_25_data_3_Width 7
`define scan_in_inst_25_data_3_LSbit_Addr 141
`define scan_in_inst_25_data_3_MSbit_Addr 142
`define scan_in_inst_25_data_3_LSbit_Pos 7
`define scan_in_inst_25_data_3_MSbit_Pos 5
// Defines for register "scan_in_inst_26_data_3"
`define scan_in_inst_26_data_3_LSbit 1142
`define scan_in_inst_26_data_3_MSbit 1148
`define scan_in_inst_26_data_3_Sel 1148:1142
`define scan_in_inst_26_data_3_Width 7
`define scan_in_inst_26_data_3_LSbit_Addr 142
`define scan_in_inst_26_data_3_MSbit_Addr 143
`define scan_in_inst_26_data_3_LSbit_Pos 6
`define scan_in_inst_26_data_3_MSbit_Pos 4
// Defines for register "scan_in_inst_27_data_3"
`define scan_in_inst_27_data_3_LSbit 1149
`define scan_in_inst_27_data_3_MSbit 1155
`define scan_in_inst_27_data_3_Sel 1155:1149
`define scan_in_inst_27_data_3_Width 7
`define scan_in_inst_27_data_3_LSbit_Addr 143
`define scan_in_inst_27_data_3_MSbit_Addr 144
`define scan_in_inst_27_data_3_LSbit_Pos 5
`define scan_in_inst_27_data_3_MSbit_Pos 3
// Defines for register "scan_in_inst_28_data_3"
`define scan_in_inst_28_data_3_LSbit 1156
`define scan_in_inst_28_data_3_MSbit 1162
`define scan_in_inst_28_data_3_Sel 1162:1156
`define scan_in_inst_28_data_3_Width 7
`define scan_in_inst_28_data_3_LSbit_Addr 144
`define scan_in_inst_28_data_3_MSbit_Addr 145
`define scan_in_inst_28_data_3_LSbit_Pos 4
`define scan_in_inst_28_data_3_MSbit_Pos 2
// Defines for register "scan_in_inst_29_data_3"
`define scan_in_inst_29_data_3_LSbit 1163
`define scan_in_inst_29_data_3_MSbit 1169
`define scan_in_inst_29_data_3_Sel 1169:1163
`define scan_in_inst_29_data_3_Width 7
`define scan_in_inst_29_data_3_LSbit_Addr 145
`define scan_in_inst_29_data_3_MSbit_Addr 146
`define scan_in_inst_29_data_3_LSbit_Pos 3
`define scan_in_inst_29_data_3_MSbit_Pos 1
// Defines for register "scan_in_inst_30_data_3"
`define scan_in_inst_30_data_3_LSbit 1170
`define scan_in_inst_30_data_3_MSbit 1176
`define scan_in_inst_30_data_3_Sel 1176:1170
`define scan_in_inst_30_data_3_Width 7
`define scan_in_inst_30_data_3_LSbit_Addr 146
`define scan_in_inst_30_data_3_MSbit_Addr 147
`define scan_in_inst_30_data_3_LSbit_Pos 2
`define scan_in_inst_30_data_3_MSbit_Pos 0
// Defines for register "scan_in_inst_31_data_3"
`define scan_in_inst_31_data_3_LSbit 1177
`define scan_in_inst_31_data_3_MSbit 1183
`define scan_in_inst_31_data_3_Sel 1183:1177
`define scan_in_inst_31_data_3_Width 7
`define scan_in_inst_31_data_3_LSbit_Addr 147
`define scan_in_inst_31_data_3_MSbit_Addr 147
`define scan_in_inst_31_data_3_LSbit_Pos 1
`define scan_in_inst_31_data_3_MSbit_Pos 7
// Defines for register "scan_in_inst_req_3"
`define scan_in_inst_req_3_LSbit 1184
`define scan_in_inst_req_3_MSbit 1184
`define scan_in_inst_req_3_Sel 1184:1184
`define scan_in_inst_req_3_Width 1
`define scan_in_inst_req_3_LSbit_Addr 148
`define scan_in_inst_req_3_MSbit_Addr 148
`define scan_in_inst_req_3_LSbit_Pos 0
`define scan_in_inst_req_3_MSbit_Pos 0
// Defines for register "scan_in_inst_cmd_3"
`define scan_in_inst_cmd_3_LSbit 1185
`define scan_in_inst_cmd_3_MSbit 1186
`define scan_in_inst_cmd_3_Sel 1186:1185
`define scan_in_inst_cmd_3_Width 2
`define scan_in_inst_cmd_3_LSbit_Addr 148
`define scan_in_inst_cmd_3_MSbit_Addr 148
`define scan_in_inst_cmd_3_LSbit_Pos 1
`define scan_in_inst_cmd_3_MSbit_Pos 2
// Defines for register "scan_in_inst_ack_3"
`define scan_in_inst_ack_3_LSbit 1187
`define scan_in_inst_ack_3_MSbit 1187
`define scan_in_inst_ack_3_Sel 1187:1187
`define scan_in_inst_ack_3_Width 1
`define scan_in_inst_ack_3_LSbit_Addr 148
`define scan_in_inst_ack_3_MSbit_Addr 148
`define scan_in_inst_ack_3_LSbit_Pos 3
`define scan_in_inst_ack_3_MSbit_Pos 3
// Field INSTRUCTION_3 length
`define INSTRUCTION_3_field_bit_length 228
`define INSTRUCTION_3_field_byte_length 29

/**************/
/* Field: I2C */
/**************/
`define I2C_field_addr 149
// Defines for register "i2c_req"
`define i2c_req_LSbit 1192
`define i2c_req_MSbit 1192
`define i2c_req_Sel 1192:1192
`define i2c_req_Width 1
`define i2c_req_LSbit_Addr 149
`define i2c_req_MSbit_Addr 149
`define i2c_req_LSbit_Pos 0
`define i2c_req_MSbit_Pos 0
// Defines for register "i2c_slave_address"
`define i2c_slave_address_LSbit 1193
`define i2c_slave_address_MSbit 1199
`define i2c_slave_address_Sel 1199:1193
`define i2c_slave_address_Width 7
`define i2c_slave_address_LSbit_Addr 149
`define i2c_slave_address_MSbit_Addr 149
`define i2c_slave_address_LSbit_Pos 1
`define i2c_slave_address_MSbit_Pos 7
// Defines for register "i2c_burst_count_wr"
`define i2c_burst_count_wr_LSbit 1200
`define i2c_burst_count_wr_MSbit 1201
`define i2c_burst_count_wr_Sel 1201:1200
`define i2c_burst_count_wr_Width 2
`define i2c_burst_count_wr_LSbit_Addr 150
`define i2c_burst_count_wr_MSbit_Addr 150
`define i2c_burst_count_wr_LSbit_Pos 0
`define i2c_burst_count_wr_MSbit_Pos 1
// Defines for register "i2c_burst_count_rd"
`define i2c_burst_count_rd_LSbit 1202
`define i2c_burst_count_rd_MSbit 1203
`define i2c_burst_count_rd_Sel 1203:1202
`define i2c_burst_count_rd_Width 2
`define i2c_burst_count_rd_LSbit_Addr 150
`define i2c_burst_count_rd_MSbit_Addr 150
`define i2c_burst_count_rd_LSbit_Pos 2
`define i2c_burst_count_rd_MSbit_Pos 3
// Defines for register "i2c_wdata0"
`define i2c_wdata0_LSbit 1204
`define i2c_wdata0_MSbit 1211
`define i2c_wdata0_Sel 1211:1204
`define i2c_wdata0_Width 8
`define i2c_wdata0_LSbit_Addr 150
`define i2c_wdata0_MSbit_Addr 151
`define i2c_wdata0_LSbit_Pos 4
`define i2c_wdata0_MSbit_Pos 3
// Defines for register "i2c_wdata1"
`define i2c_wdata1_LSbit 1212
`define i2c_wdata1_MSbit 1219
`define i2c_wdata1_Sel 1219:1212
`define i2c_wdata1_Width 8
`define i2c_wdata1_LSbit_Addr 151
`define i2c_wdata1_MSbit_Addr 152
`define i2c_wdata1_LSbit_Pos 4
`define i2c_wdata1_MSbit_Pos 3
// Defines for register "i2c_wdata2"
`define i2c_wdata2_LSbit 1220
`define i2c_wdata2_MSbit 1227
`define i2c_wdata2_Sel 1227:1220
`define i2c_wdata2_Width 8
`define i2c_wdata2_LSbit_Addr 152
`define i2c_wdata2_MSbit_Addr 153
`define i2c_wdata2_LSbit_Pos 4
`define i2c_wdata2_MSbit_Pos 3
// Defines for register "i2c_wdata3"
`define i2c_wdata3_LSbit 1228
`define i2c_wdata3_MSbit 1235
`define i2c_wdata3_Sel 1235:1228
`define i2c_wdata3_Width 8
`define i2c_wdata3_LSbit_Addr 153
`define i2c_wdata3_MSbit_Addr 154
`define i2c_wdata3_LSbit_Pos 4
`define i2c_wdata3_MSbit_Pos 3
// Defines for register "i2c_rd_wrn"
`define i2c_rd_wrn_LSbit 1236
`define i2c_rd_wrn_MSbit 1236
`define i2c_rd_wrn_Sel 1236:1236
`define i2c_rd_wrn_Width 1
`define i2c_rd_wrn_LSbit_Addr 154
`define i2c_rd_wrn_MSbit_Addr 154
`define i2c_rd_wrn_LSbit_Pos 4
`define i2c_rd_wrn_MSbit_Pos 4
// Defines for register "i2c_ack"
`define i2c_ack_LSbit 1237
`define i2c_ack_MSbit 1237
`define i2c_ack_Sel 1237:1237
`define i2c_ack_Width 1
`define i2c_ack_LSbit_Addr 154
`define i2c_ack_MSbit_Addr 154
`define i2c_ack_LSbit_Pos 5
`define i2c_ack_MSbit_Pos 5
// Defines for register "i2c_nack"
`define i2c_nack_LSbit 1238
`define i2c_nack_MSbit 1238
`define i2c_nack_Sel 1238:1238
`define i2c_nack_Width 1
`define i2c_nack_LSbit_Addr 154
`define i2c_nack_MSbit_Addr 154
`define i2c_nack_LSbit_Pos 6
`define i2c_nack_MSbit_Pos 6
// Defines for register "i2c_rdata0"
`define i2c_rdata0_LSbit 1239
`define i2c_rdata0_MSbit 1246
`define i2c_rdata0_Sel 1246:1239
`define i2c_rdata0_Width 8
`define i2c_rdata0_LSbit_Addr 154
`define i2c_rdata0_MSbit_Addr 155
`define i2c_rdata0_LSbit_Pos 7
`define i2c_rdata0_MSbit_Pos 6
// Defines for register "i2c_rdata1"
`define i2c_rdata1_LSbit 1247
`define i2c_rdata1_MSbit 1254
`define i2c_rdata1_Sel 1254:1247
`define i2c_rdata1_Width 8
`define i2c_rdata1_LSbit_Addr 155
`define i2c_rdata1_MSbit_Addr 156
`define i2c_rdata1_LSbit_Pos 7
`define i2c_rdata1_MSbit_Pos 6
// Defines for register "i2c_rdata2"
`define i2c_rdata2_LSbit 1255
`define i2c_rdata2_MSbit 1262
`define i2c_rdata2_Sel 1262:1255
`define i2c_rdata2_Width 8
`define i2c_rdata2_LSbit_Addr 156
`define i2c_rdata2_MSbit_Addr 157
`define i2c_rdata2_LSbit_Pos 7
`define i2c_rdata2_MSbit_Pos 6
// Defines for register "i2c_rdata3"
`define i2c_rdata3_LSbit 1263
`define i2c_rdata3_MSbit 1270
`define i2c_rdata3_Sel 1270:1263
`define i2c_rdata3_Width 8
`define i2c_rdata3_LSbit_Addr 157
`define i2c_rdata3_MSbit_Addr 158
`define i2c_rdata3_LSbit_Pos 7
`define i2c_rdata3_MSbit_Pos 6
// Field I2C length
`define I2C_field_bit_length 79
`define I2C_field_byte_length 10
